/**
 * @file     crc.h (180.ARM_Peripherals/Project_Headers/crc.h)
 * @brief    External Watchdog Monitor
 */

#ifndef HEADER_CRC_H_
#define HEADER_CRC_H_

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "derivative.h"
#include "pin_mapping.h"

// $/CRC/prototypes not found

namespace USBDM {

/**
 * @addtogroup CRC_Group CRC, Cyclic Redundancy Check
 * @brief Abstraction for Cyclic Redundancy Check
 * @{
 */
/**
 * Peripheral information for CRC, Cyclic Redundancy Check.
 * 
 * This may include pin information, constants, register addresses, and default register values,
 * along with simple accessor functions.
 */

   /**
    * CRC Polynomial
    * (crc_gpoly_gpoly)
    *
    * Polynomial used for the CRC calculation
    */
   enum CrcPolynomial : uint32_t {
   };

   /**
    * CRC Seed
    * (crc_data_data)
    *
    * Seed value used for the CRC calculation
    */
   enum CrcSeed : uint32_t {
   };

   /**
    * Type of Transpose For Writes
    * (crc_ctrl_tot)
    *
    * Define the transpose configuration for values written to the CRC data register
    * Controls transposition of bits within the bytes and bytes within the whole value
    */
   enum CrcWriteTranspose : uint32_t {
      CrcWriteTranspose_NoTransposition          = CRC_CTRL_TOT(0),  ///< No transposition
      CrcWriteTranspose_BitsTransposed           = CRC_CTRL_TOT(1),  ///< Bits transposed
      CrcWriteTranspose_BitsAndBytesTransposed   = CRC_CTRL_TOT(2),  ///< Bits and bytes transposed
      CrcWriteTranspose_BytesTransposed          = CRC_CTRL_TOT(3),  ///< Bytes transposed
   };

   /**
    * Type of Transpose For Read
    * (crc_ctrl_totr)
    *
    * Identify the transpose configuration of values read from the CRC Data register.
    * Controls transposition of bits within the bytes and bytes within the whole value
    */
   enum CrcReadTranspose : uint32_t {
      CrcReadTranspose_NoTransposition          = CRC_CTRL_TOTR(0),  ///< No transposition
      CrcReadTranspose_BitsTransposed           = CRC_CTRL_TOTR(1),  ///< Bits transposed
      CrcReadTranspose_BitsAndBytesTransposed   = CRC_CTRL_TOTR(2),  ///< Bits and bytes transposed
      CrcReadTranspose_BytesTransposed          = CRC_CTRL_TOTR(3),  ///< Bytes transposed
   };

   /**
    * Complement Read Of CRC Data Register
    * (crc_ctrl_fxor)
    *
    * Some CRC protocols require the final checksum to be XORed with 0xFFFFFFFF or 0xFFFF.
    * Asserting this bit enables on the fly complementing of read data
    */
   enum CrcReadComplement : uint32_t {
      CrcReadComplement_Normal     = CRC_CTRL_FXOR(0),  ///< No inversion
      CrcReadComplement_Inverted   = CRC_CTRL_FXOR(1),  ///< Invert read of data register
   };

   /**
    * Write CRC Data Register As Seed
    * (crc_ctrl_was)
    *
    * Selects between seed or data value when a value is written to the CRC data register
    */
   enum CrcWriteMode : uint32_t {
      CrcWriteMode_WritesData   = CRC_CTRL_WAS(0),  ///< Writes are data values
      CrcWriteMode_WritesSeed   = CRC_CTRL_WAS(1),  ///< Writes are seed values
   };

   /**
    * Width of CRC protocol
    * (crc_ctrl_tcrc)
    *
    * Width used in CRC calculation
    */
   enum CrcWidth : uint32_t {
      CrcWidth_16BitCrc   = CRC_CTRL_TCRC(0),  ///< 16-bit CRC
      CrcWidth_32BitCrc   = CRC_CTRL_TCRC(1),  ///< 32-bit CRC
   };

class CrcBasicInfo {

public:

   // Pointer to CRC hardware instance
   volatile CRC_Type * const crc;
   
   /**
    * Constructor
    *
    * @param crc CRC hardware instance
    */
   constexpr CrcBasicInfo(volatile CRC_Type * crc) : crc(crc) {
   }
   
   /**
    * Write polynomial value used for CRC calculation.
    * (crc_gpoly_gpoly)
    *
    * @param polynomialValue Polynomial value used for CRC calculation
    */
   void writePolynomial(uint32_t polynomialValue) const {
      crc->GPOLY = polynomialValue;
   }
   
   /**
    * Get polynomial value used for CRC calculation.
    * (crc_gpoly_gpoly)
    *
    * @return Polynomial value used for CRC calculation
    */
   uint32_t getPolynomial() const {
      uint32_t data = crc->GPOLY;
      if ((crc->CTRL&CRC_CTRL_TCRC_MASK) == 0) {
         data &= 0xFFFF;
      }
      return data;
   }
   
   /**
    * Write seed value for CRC calculation.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @param seedValue  Seed value to initialise CRC calculation
    */
   void writeSeed(uint32_t seedValue) const {
      crc->CTRL = crc->CTRL | CRC_CTRL_WAS_MASK;
      crc->DATA = seedValue;
      crc->CTRL = crc->CTRL & ~CRC_CTRL_WAS_MASK;
   }
   
   /**
    * Write data value for CRC calculation.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @tparam T         Type of data (inferred)
    *
    * @param dataValue  Data value for CRC calculation
    */
   template<typename T>
   void writeData(T dataValue) const {
      static_assert((sizeof(T)==1)||(sizeof(T)==2)||(sizeof(T)==4));
      crc->DATA = dataValue;
   }
   
   /**
    * Get calculated CRC value.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @return Calculated CRC value
    */
   uint32_t getCalculatedCrc() const {
      uint32_t data = crc->DATA;
      if ((crc->CTRL&CRC_CTRL_TCRC_MASK) == 0) {
         // Truncate to 16-bit value
         data &= 0xFFFF;
      }
      return data;
   }
   
   /**
    * Class used to do initialisation of the Crc
    *
    * This class has a templated constructor that accepts various values.
    * Parameters available may vary with device - see Crc0::DefaultInitValue for relevant example.
    * Omitted parameters default to zero (disabled) or unchanged if initialiser is provided as last parameter.
    *
    * @note This constructor may be used to create a const instance in Flash
    *
    * Example:
    * @code
    * static const Crc0::Init crc0Init {
    *
    *   // Setup values
    *   CrcPolynomial(0x0) ,                // CRC Polynomial
    *   CrcSeed(0x0) ,                      // CRC Seed
    *   CrcWriteTranspose_NoTransposition , // Type of Transpose For Writes - No transposition
    *   CrcReadTranspose_NoTransposition ,  // Type of Transpose For Read - No transposition
    *   CrcReadComplement_Normal ,          // Complement Read Of CRC Data Register - No inversion
    *   CrcWidth_16BitCrc,                  // Width of CRC protocol - 16-bit CRC
    * };
    *
    * // Initialise Crc0 from values specified above
    * Crc0::configure(crc0Init)
    * @endcode
    */
   class Init {
   
   private:
      /**
       * Prevent implicit parameter conversions
       */
      template <typename... Types>
      constexpr Init(Types...) = delete;
   
   public:
      /**
       * Copy Constructor
       */
      constexpr Init(const Init &other) = default;
   
      /**
       * Default Constructor
       */
      constexpr Init() = default;
   
      // CRC Polynomial (crc_gpoly_gpoly)
      uint32_t gpoly = 0;

      // CRC Seed (crc_data_data)
      uint32_t data = 0;

      // Type of Transpose For Writes (crc_ctrl_tot)
      // Type of Transpose For Read (crc_ctrl_totr)
      // Complement Read Of CRC Data Register (crc_ctrl_fxor)
      // Width of CRC protocol (crc_ctrl_tcrc)
      uint32_t ctrl = 0;

      /**
       * Constructor for Type of Transpose For Writes
       * (crc_ctrl_tot)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcWriteTranspose Define the transpose configuration for values written to the CRC data register
       *        Controls transposition of bits within the bytes and bytes within the whole value
       */
      template <typename... Types>
      constexpr Init(CrcWriteTranspose crcWriteTranspose, Types... rest) : Init(rest...) {
   
         ctrl = (ctrl&~CRC_CTRL_TOT_MASK) | uint32_t(crcWriteTranspose);
      }
   
      /**
       * Constructor for Type of Transpose For Read
       * (crc_ctrl_totr)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcReadTranspose Identify the transpose configuration of values read from the CRC Data register.
       *        Controls transposition of bits within the bytes and bytes within the whole value
       */
      template <typename... Types>
      constexpr Init(CrcReadTranspose crcReadTranspose, Types... rest) : Init(rest...) {
   
         ctrl = (ctrl&~CRC_CTRL_TOTR_MASK) | uint32_t(crcReadTranspose);
      }
   
      /**
       * Constructor for Complement Read Of CRC Data Register
       * (crc_ctrl_fxor)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcReadComplement Some CRC protocols require the final checksum to be XORed with 0xFFFFFFFF or 0xFFFF.
       *        Asserting this bit enables on the fly complementing of read data
       */
      template <typename... Types>
      constexpr Init(CrcReadComplement crcReadComplement, Types... rest) : Init(rest...) {
   
         ctrl = (ctrl&~CRC_CTRL_FXOR_MASK) | uint32_t(crcReadComplement);
      }
   
      /**
       * Constructor for Width of CRC protocol
       * (crc_ctrl_tcrc)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcWidth Width used in CRC calculation
       */
      template <typename... Types>
      constexpr Init(CrcWidth crcWidth, Types... rest) : Init(rest...) {
   
         ctrl = (ctrl&~CRC_CTRL_TCRC_MASK) | uint32_t(crcWidth);
      }
   
      /**
       * Constructor for CRC Polynomial
       * (crc_gpoly_gpoly)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcPolynomial Polynomial used for the CRC calculation
       */
      template <typename... Types>
      constexpr Init(CrcPolynomial crcPolynomial, Types... rest) : Init(rest...) {
   
         gpoly = (gpoly&~CRC_GPOLY_GPOLY_MASK) | uint32_t(CRC_GPOLY_GPOLY(crcPolynomial));
      }
   
      /**
       * Constructor for CRC Seed
       * (crc_data_data)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param crcSeed Seed value used for the CRC calculation
       */
      template <typename... Types>
      constexpr Init(CrcSeed crcSeed, Types... rest) : Init(rest...) {
   
         data = (data&~CRC_DATA_DATA_MASK) | uint32_t(CRC_DATA_DATA(crcSeed));
      }
   
   }; // class CrcBasicInfo::Init
   
   /**
    * Configure CRC from values specified in init
    *
    * @param crc           Hardware instance pointer
    * @param init Class containing initialisation values
    */
   static void configure(
                  volatile CRC_Type *crc,
                  const Init    &init) {
   
   
   
      // Write CRC Data Register As Seed (crc_ctrl_was)
      // Type of Transpose For Writes (crc_ctrl_tot)
      // Type of Transpose For Read (crc_ctrl_totr)
      // Complement Read Of CRC Data Register (crc_ctrl_fxor)
      // Width of CRC protocol (crc_ctrl_tcrc)
      crc->CTRL = init.ctrl|CRC_CTRL_WAS_MASK;
   
      // CRC Seed (crc_data_data)
      crc->DATA = init.data;
   
      // CRC Polynomial (crc_gpoly_gpoly)
      crc->GPOLY = init.gpoly;
   
      // Type of Transpose For Writes (crc_ctrl_tot)
      // Type of Transpose For Read (crc_ctrl_totr)
      // Complement Read Of CRC Data Register (crc_ctrl_fxor)
      // Width of CRC protocol (crc_ctrl_tcrc)
      crc->CTRL = init.ctrl;
   }
   
   /**
    * Configure CRC from values specified in init
    * This routine does not configure pins or interrupt handlers
    *
    * @param init Class containing initialisation values
    */
   void configure(const Init &init) const {
   
      configure(crc, init);
   }
   
   /**
    * Cumulatively calculate CRC over an array
    * Assumes CRC has been initialised before 1st use using
    * configure(...) or calculateCrc(const Init &init, ...).
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    *
    * @param data       Data to calculate CRC over
    * @param numEntries Size of data array in elements
    *
    * @return  Calculated CRC
    */
   template<typename T>
   uint32_t calculateCrc(const T data[], unsigned numEntries) const {
   
      // Write data to CRC unit i.e. calculate CRC
      for(unsigned index=0; index<numEntries; index++) {
         crc->DATA = data[index];
      }
      // Return result
      return getCalculatedCrc();
   }
   
   /**
    * Calculate CRC over an array
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    *
    * @param init       CRC initialisation information
    * @param data       Data to calculate CRC over
    * @param numEntries Size of data array in elements
    *
    * @return  Calculated CRC
    */
   template<typename T>
   uint32_t calculateCrc(const Init &init, const T *data, unsigned numEntries) const {
   
      configure(init);
      return calculateCrc(data, numEntries);
   }
   
   /**
    * Calculate CRC over an array
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    * @tparam N         Size of data array in elements (inferred)
    *
    * @param init       CRC initialisation information
    * @param data       Data to calculate CRC over
    *
    * @return  Calculated CRC
    */
   template<typename T, size_t N>
   uint32_t calculateCrc(const Init &init, const T (&data)[N]) const {
   
      return calculateCrc(init, data, N);
   }
   
}; // class CrcBasicInfo 

class Crc0Info : public CrcBasicInfo {

public:

   /*
    * Template:crc0_0x40032000
    */
   /**
    *  Enable clock to Crc0
    */
   static void enableClock() {
      SIM->SCGC6 = SIM->SCGC6 | SIM_SCGC6_CRC_MASK;
   }
   
   /**
    *  Disable clock to Crc0
    */
   static void disableClock() {
      SIM->SCGC6 = SIM->SCGC6 & ~SIM_SCGC6_CRC_MASK;
   }
   
   /**
    * Basic enable of Crc0
    * Includes enabling clock and configuring all mapped pins if mapPinsOnEnable is selected in configuration
    */
   static void enable() {
      enableClock();
   }
   
   /**
    * Disables Crc0
    */
   static void disable() {
   
      
      disableClock();
   }
   
   //! Hardware base address as uint32_t
   static constexpr uint32_t baseAddress = CRC0_BasePtr;
   
   //! Hardware base pointer
   static constexpr HardwarePtr<CRC_Type> crc = baseAddress;
   
   //! Peripheral instance number
   static constexpr unsigned instance = 0;
   
   /**
    * Write polynomial value used for CRC calculation.
    * (crc_gpoly_gpoly)
    *
    * @param polynomialValue Polynomial value used for CRC calculation
    */
   static void writePolynomial(uint32_t polynomialValue) {
      crc->GPOLY = polynomialValue;
   }
   
   /**
    * Get polynomial value used for CRC calculation.
    * (crc_gpoly_gpoly)
    *
    * @return Polynomial value used for CRC calculation
    */
   static uint32_t getPolynomial() {
      uint32_t data = crc->GPOLY;
      if ((crc->CTRL&CRC_CTRL_TCRC_MASK) == 0) {
         data &= 0xFFFF;
      }
      return data;
   }
   
   /**
    * Write seed value for CRC calculation.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @param seedValue  Seed value to initialise CRC calculation
    */
   static void writeSeed(uint32_t seedValue) {
      crc->CTRL = crc->CTRL | CRC_CTRL_WAS_MASK;
      crc->DATA = seedValue;
      crc->CTRL = crc->CTRL & ~CRC_CTRL_WAS_MASK;
   }
   
   /**
    * Write data value for CRC calculation.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @tparam T         Type of data (inferred)
    *
    * @param dataValue  Data value for CRC calculation
    */
   template<typename T>
   static void writeData(T dataValue) {
      static_assert((sizeof(T)==1)||(sizeof(T)==2)||(sizeof(T)==4));
      crc->DATA = dataValue;
   }
   
   /**
    * Get calculated CRC value.
    * (crc_data_data,crc_ctrl_was,crc_ctrl_tcrc)
    *
    * @return Calculated CRC value
    */
   static uint32_t getCalculatedCrc() {
      uint32_t data = crc->DATA;
      if ((crc->CTRL&CRC_CTRL_TCRC_MASK) == 0) {
         // Truncate to 16-bit value
         data &= 0xFFFF;
      }
      return data;
   }
   
   /**
    * Configure CRC-16/CCIT-FALSE
    * See http://reveng.sourceforge.net/crc-catalogue/
    */
   static constexpr Init Crc16_ccit_false {
      CrcWidth_16BitCrc,
      CrcWriteTranspose_NoTransposition,
      CrcReadTranspose_NoTransposition,
      CrcReadComplement_Normal,
      CrcPolynomial(0x1021),
      CrcSeed(0xFFFF)
   };
   
   /**
    * Configure ARC (aka CRC-16)
    * See http://reveng.sourceforge.net/crc-catalogue/
    */
   static constexpr Init Crc16 {
      CrcWidth_16BitCrc,
      CrcWriteTranspose_BitsAndBytesTransposed,
      CrcReadTranspose_BitsAndBytesTransposed,
      CrcReadComplement_Normal,
      CrcPolynomial(0x8005),
      CrcSeed(0x0000)
   };
   
   /**
    * Configure CRC-32
    * See http://reveng.sourceforge.net/crc-catalogue/
    */
   static constexpr Init Crc32 {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_BitsAndBytesTransposed,
      CrcReadTranspose_BitsAndBytesTransposed,
      CrcReadComplement_Inverted,
      CrcPolynomial(0x04c11db7),
      CrcSeed(0xffffffff)
   };
   
   /**
    * Configure CRC-32/BZIP
    * See https://crccalc.com/
    */
   static constexpr Init Crc32_BZIP {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_NoTransposition,
      CrcReadTranspose_NoTransposition,
      CrcReadComplement_Inverted,
      CrcPolynomial(0x04c11db7),
      CrcSeed(0xffffffff)
   };
   
   /**
    * Configure CRC-32-C
    * See https://crccalc.com/
    */
   static constexpr Init Crc32_C {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_BitsAndBytesTransposed,
      CrcReadTranspose_BitsAndBytesTransposed,
      CrcReadComplement_Inverted,
      CrcPolynomial(0x1EDC6F41),
      CrcSeed(0xffffffff)
   };
   
   /**
    * Configure CRC-32-D
    * See https://crccalc.com/
    */
   static constexpr Init Crc32_D {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_BitsAndBytesTransposed,
      CrcReadTranspose_BitsAndBytesTransposed,
      CrcReadComplement_Inverted,
      CrcPolynomial(0xA833982B),
      CrcSeed(0xffffffff)
   };
   
   /**
    * Configure CRC-32/MPEG-2
    * See https://crccalc.com/
    */
   static constexpr Init Crc32_MPEG_2 {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_NoTransposition,
      CrcReadTranspose_NoTransposition,
      CrcReadComplement_Normal,
      CrcPolynomial(0x04c11db7),
      CrcSeed(0xffffffff)
   };
   
   /**
    * Configure CRC-32/POSIX
    * See https://crccalc.com/
    */
   static constexpr Init Crc32_POSIX {
      CrcWidth_32BitCrc,
      CrcWriteTranspose_NoTransposition,
      CrcReadTranspose_NoTransposition,
      CrcReadComplement_Inverted,
      CrcPolynomial(0x04c11db7),
      CrcSeed(0x00000000)
   };
   
   /**
    * Cumulatively calculate CRC over an array
    * Assumes CRC has been initialised before 1st use using
    * configure(...) or calculateCrc(const Init &init, ...).
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    *
    * @param data       Data to calculate CRC over
    * @param numEntries Size of data array in elements
    *
    * @return  Calculated CRC
    */
   template<typename T>
   static uint32_t calculateCrc(const T data[], unsigned numEntries) {
   
      // Write data to CRC unit i.e. calculate CRC
      for(unsigned index=0; index<numEntries; index++) {
         crc->DATA = data[index];
      }
      // Return result
      return getCalculatedCrc();
   }
   
   /**
    * Calculate CRC over an array
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    *
    * @param init       CRC initialisation information
    * @param data       Data to calculate CRC over
    * @param numEntries Size of data array in elements
    *
    * @return  Calculated CRC
    */
   template<typename T>
   static uint32_t calculateCrc(const Init &init, const T *data, unsigned numEntries) {
   
      configure(init);
      return calculateCrc(data, numEntries);
   }
   
   /**
    * Calculate CRC over an array
    * (crc_data_data)
    *
    * @tparam T         Type of data in array (inferred)
    * @tparam N         Size of data array in elements (inferred)
    *
    * @param init       CRC initialisation information
    * @param data       Data to calculate CRC over
    *
    * @return  Calculated CRC
    */
   template<typename T, size_t N>
   static uint32_t calculateCrc(const Init &init, const T (&data)[N]) {
   
      return calculateCrc(init, data, N);
   }
   
   /**
    * Configure with default settings.
    * Configuration determined from Configure.usbdmProject
    */
   static void defaultConfigure() {
   
      configure(DefaultInitValue);
   }
   
   /**
    * Configure CRC from values specified in init
    *
    * @param init Class containing initialisation values
    */
   static void configure(const Init &init) {
   
      // Enable peripheral
      enable();
   
      CrcBasicInfo::configure(crc, init);
   }
   
   /*
    *   Default Constructor
    */
   Crc0Info() : CrcBasicInfo(crc) {
      defaultConfigure();
   }
   
   /*
    *   Constructor
    */
   Crc0Info(const Init &init) : CrcBasicInfo(crc) {
      configure(init);
   }
   
   /**
    * Default initialisation value for Crc0
    * This value is created from Configure.usbdmProject settings
    */
   static constexpr Init DefaultInitValue = {
      CrcPolynomial(0x0) ,                        // (crc_gpoly_gpoly)          CRC Polynomial
      CrcSeed(0x0) ,                              // (crc_data_data)            CRC Seed
      CrcWriteTranspose_NoTransposition ,         // (crc_ctrl_tot)             Type of Transpose For Writes - No transposition
      CrcReadTranspose_NoTransposition ,          // (crc_ctrl_totr)            Type of Transpose For Read - No transposition
      CrcReadComplement_Normal ,                  // (crc_ctrl_fxor)            Complement Read Of CRC Data Register - No inversion
      CrcWidth_16BitCrc,                          // (crc_ctrl_tcrc)            Width of CRC protocol - 16-bit CRC
   };
   
}; // class Crc0Info




   /**
    * Class representing CRC instance
    */
   typedef CrcBasicInfo Crc;
   /**
    * Class representing CRC0
    */
   typedef Crc0Info Crc0;
   

/**
 * End CRC_Group
 * @}
 */
} // End namespace USBDM

#endif /* HEADER_CRC_H_ */
