/**
 * @file     spi.h (180.ARM_Peripherals/Project_Headers/spi-MK.h)
 * @brief    Serial Peripheral Interface
 */

#ifndef INCLUDE_USBDM_SPI_H_
#define INCLUDE_USBDM_SPI_H_

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#if false // /SPI/_BasicInfoGuard

#include "pin_mapping.h"
#include "gpio.h"

#include "dma.h"

#ifdef __CMSIS_RTOS
#include "cmsis.h"
#endif

// No handler defined for SPI0


namespace USBDM {

/**
 * @addtogroup SPI_Group SPI, Serial Peripheral Interface
 * @brief C++ Class allowing access to SPI interface
 * @{
 */
/**
 * Peripheral information for SPI, Serial Peripheral Interface.
 * 
 * This may include pin information, constants, register addresses, and default register values,
 * along with simple accessor functions.
 */

   /**
    * Transfer Counter
    * (spi_tcr_spi_tcnt)
    *
    * 
    */
   enum SpiTransferCounter : uint16_t {
   };

   /**
    * Transfer Complete Flag
    * (spi_sr_tcf)
    *
    * 
    */
   enum SpiTransferFlag : uint32_t {
      SpiTransferFlag_NotComplete   = SPI_SR_TCF(0),  ///< Transfer not complete
      SpiTransferFlag_Complete      = SPI_SR_TCF(1),  ///< Transfer complete
   };

   /**
    * TX and RX Status
    * (spi_sr_txrxs)
    *
    * Indicates the status of transmit and receive operations
    */
   enum SpiTxAndRxStatus : uint32_t {
      SpiTxAndRxStatus_TxRxDisabled   = SPI_SR_TXRXS(0),  ///< Tx/Rx disabled
      SpiTxAndRxStatus_TxRxEnabled    = SPI_SR_TXRXS(1),  ///< Tx/Rx enabled
   };

   /**
    * End of Queue Flag
    * (spi_sr_eoqf)
    *
    * Indicates if EOQ is set in the executing command
    */
   enum SpiEndOfQueueFlag : uint32_t {
      SpiEndOfQueueFlag_EoqNotSet   = SPI_SR_EOQF(0),  ///< EOQ not set
      SpiEndOfQueueFlag_EoqSet      = SPI_SR_EOQF(1),  ///< EOQ set
   };

   /**
    * Transmit FIFO Underflow Flag
    * (spi_sr_tfuf)
    *
    * 
    */
   enum SpiTransmitFifoUnderflowFlag : uint32_t {
      SpiTransmitFifoUnderflowFlag_NoTxFifoUnderflow   = SPI_SR_TFUF(0),  ///< No Tx FIFO underflow
      SpiTransmitFifoUnderflowFlag_TxFifoUnderflow     = SPI_SR_TFUF(1),  ///< Tx FIFO underflow
   };

   /**
    * Transmit FIFO Fill Flag
    * (spi_sr_tfff)
    *
    * 
    */
   enum SpiTransmitFifoFillFlag : uint32_t {
      SpiTransmitFifoFillFlag_TxFifoIsFull      = SPI_SR_TFFF(0),  ///< Tx FIFO is full
      SpiTransmitFifoFillFlag_TxFifoIsNotFull   = SPI_SR_TFFF(1),  ///< Tx FIFO is not full
   };

   /**
    * Receive FIFO Overflow Flag
    * (spi_sr_rfof)
    *
    * Indicates an overflow condition in the RX FIFO.
    * The field is set when the RX FIFO and shift register are full and a transfer is initiated.
    * The bit remains set until it is cleared by writing a 1 to it
    */
   enum SpiReceiveFifoOverflowFlag : uint32_t {
      SpiReceiveFifoOverflowFlag_NoRxFifoOverflow            = SPI_SR_RFOF(0),  ///< No Rx FIFO overflow
      SpiReceiveFifoOverflowFlag_RxFifoOverflowHasOccurred   = SPI_SR_RFOF(1),  ///< Rx FIFO overflow has occurred
   };

   /**
    * Receive FIFO Drain Flag
    * (spi_sr_rfdf)
    *
    * Provides a method for the SPI to request that entries be removed from the RX FIFO.
    * The bit is set while the RX FIFO is not empty.
    * The RFDF bit can be cleared by writing 1
    */
   enum SpiReceiveFifoDrainFlag : uint32_t {
      SpiReceiveFifoDrainFlag_RxFifoIsEmpty      = SPI_SR_RFDF(0),  ///< Rx FIFO is empty
      SpiReceiveFifoDrainFlag_RxFifoIsNotEmpty   = SPI_SR_RFDF(1),  ///< Rx FIFO is not empty
   };

   /**
    * Status Flags
    * (spi_sr_stat)
    *
    * These masks may be used to test or modify the status flags
    */
   enum SpiStatusFlag : uint32_t {
      SpiStatusFlag_TransferFlag                = (SPI_SR_TCF_MASK),    ///< Transfer Complete Flag
      SpiStatusFlag_TxAndRxStatus               = (SPI_SR_TXRXS_MASK),  ///< TX and RX Status
      SpiStatusFlag_EndOfQueueFlag              = (SPI_SR_EOQF_MASK),   ///< End of Queue Flag
      SpiStatusFlag_TransmitFifoUnderflowFlag   = (SPI_SR_TFUF_MASK),   ///< Transmit FIFO Underflow Flag
      SpiStatusFlag_TransmitFifoFillFlag        = (SPI_SR_TFFF_MASK),   ///< Transmit FIFO Fill Flag
      SpiStatusFlag_ReceiveFifoOverflowFlag     = (SPI_SR_RFOF_MASK),   ///< Receive FIFO Overflow Flag
      SpiStatusFlag_ReceiveFifoDrainFlag        = (SPI_SR_RFDF_MASK),   ///< Receive FIFO Drain Flag
      SpiStatusFlag_NoFlags                     = (0x0U),               ///< No flags
      SpiStatusFlag_AllFlags                    = (0xDA0A0000U),        ///< All flags
   };

   /**
    * Combines two SpiStatusFlag values (by ORing)
    * Used to create a combined SpiStatusFlag mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return  Combined value
    */
   constexpr SpiStatusFlag operator|(SpiStatusFlag left, SpiStatusFlag right) {
      return SpiStatusFlag(uint32_t(left)|uint32_t(right));
   }
   
   /**
    * Combines two SpiStatusFlag values (by ANDing) to produce a bool result
    * Used to check a value against a SpiStatusFlag mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return boolean value indicating if the result is non-zero
    */
   constexpr bool operator&(SpiStatusFlag left, SpiStatusFlag right) {
      return bool(uint32_t(left)&uint32_t(right));
   }
   
   /**
    * Tx complete action
    * (spi_rser_tcf_re)
    *
    * Enables TCF flag in the SR to generate an interrupt request
    */
   enum SpiTxCompleteAction : uint32_t {
      SpiTxCompleteAction_None        = SPI_RSER_TCF_RE(0),  ///< No requests
      SpiTxCompleteAction_Interrupt   = SPI_RSER_TCF_RE(1),  ///< Interrupt on completion
   };

   /**
    * EOQ action
    * (spi_rser_eoqf_re)
    *
    * Enables the EOQF flag in the SR to generate an interrupt request
    */
   enum SpiEndOfQueueAction : uint32_t {
      SpiEndOfQueueAction_None        = SPI_RSER_EOQF_RE(0),  ///< No requests
      SpiEndOfQueueAction_Interrupt   = SPI_RSER_EOQF_RE(1),  ///< Interrupt on end of queue
   };

   /**
    * TxFIFO Underflow action
    * (spi_rser_tfuf_re)
    *
    * Enables the TFUF flag in the SR to generate an interrupt request
    */
   enum SpiTxFifoUnderflowAction : uint32_t {
      SpiTxFifoUnderflowAction_None        = SPI_RSER_TFUF_RE(0),  ///< No requests
      SpiTxFifoUnderflowAction_Interrupt   = SPI_RSER_TFUF_RE(1),  ///< Interrupt on underflow
   };

   /**
    * Transmit FIFO Fill Request action
    * (spi_rser_txfifo)
    *
    * Transmit FIFO space action
    */
   enum SpiTxFifoAction {
      SpiTxFifoAction_None        = SPI_RSER_TFFF_RE(0)|SPI_RSER_TFFF_DIRS(0),  ///< No requests
      SpiTxFifoAction_Interrupt   = SPI_RSER_TFFF_RE(1)|SPI_RSER_TFFF_DIRS(0),  ///< Interrupt
      SpiTxFifoAction_Dma         = SPI_RSER_TFFF_RE(1)|SPI_RSER_TFFF_DIRS(1),  ///< DMA
   };

   /**
    * RxFIFO Overflow action
    * (spi_rser_rfof_re)
    *
    * Enables the RFOF flag in the SR to generate an interrupt request
    */
   enum SpiRxFifoOverflowAction : uint32_t {
      SpiRxFifoOverflowAction_None        = SPI_RSER_RFOF_RE(0),  ///< No requests
      SpiRxFifoOverflowAction_Interrupt   = SPI_RSER_RFOF_RE(1),  ///< Interrupt on overflow
   };

   /**
    * Receive FIFO Drain Request action
    * (spi_rser_rxfifo)
    *
    * Receive FIFO action
    */
   enum SpiRxFifoAction {
      SpiRxFifoAction_None        = SPI_RSER_RFDF_RE(0)|SPI_RSER_RFDF_DIRS(0),  ///< No requests
      SpiRxFifoAction_Interrupt   = SPI_RSER_RFDF_RE(1)|SPI_RSER_RFDF_DIRS(0),  ///< Interrupt
      SpiRxFifoAction_Dma         = SPI_RSER_RFDF_RE(1)|SPI_RSER_RFDF_DIRS(1),  ///< DMA
   };

   /**
    * Polarity for PCS signals
    * (spi_mcr_pcsis_enum)
    *
    * Mask to select the polarity of Peripheral Chip Select Lines (PCSx)
    * Selected PCS signals will be active-low i.e. PCS will go low when accessing the peripheral
    */
   enum SpiPcsActiveLow : uint32_t {
      SpiPcsActiveLow_Pcs0   = SPI_MCR_PCSIS(1U<<0),  ///< PCS0 is active-low
      SpiPcsActiveLow_Pcs1   = SPI_MCR_PCSIS(1U<<1),  ///< PCS1 is active-low
      SpiPcsActiveLow_Pcs2   = SPI_MCR_PCSIS(1U<<2),  ///< PCS2 is active-low
      SpiPcsActiveLow_Pcs3   = SPI_MCR_PCSIS(1U<<3),  ///< PCS3 is active-low
      SpiPcsActiveLow_Pcs4   = SPI_MCR_PCSIS(1U<<4),  ///< PCS4 is active-low
      SpiPcsActiveLow_Pcs5   = SPI_MCR_PCSIS(1U<<5),  ///< PCS5 is active-low
      SpiPcsActiveLow_None   = SPI_MCR_PCSIS(0),      ///< All PCSx active-high
      SpiPcsActiveLow_All    = SPI_MCR_PCSIS(-1),     ///< All PCSx active-low
   };

   /**
    * Combines two SpiPcsActiveLow values (by ORing)
    * Used to create a combined SpiPcsActiveLow mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return  Combined value
    */
   constexpr SpiPcsActiveLow operator|(SpiPcsActiveLow left, SpiPcsActiveLow right) {
      return SpiPcsActiveLow(uint32_t(left)|uint32_t(right));
   }
   
   /**
    * Combines two SpiPcsActiveLow values (by ANDing) to produce a bool result
    * Used to check a value against a SpiPcsActiveLow mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return boolean value indicating if the result is non-zero
    */
   constexpr bool operator&(SpiPcsActiveLow left, SpiPcsActiveLow right) {
      return bool(uint32_t(left)&uint32_t(right));
   }
   
   /**
    * Master or Slave operation
    * (spi_mcr_mstr)
    *
    * Whether to operate as Master or Slave device
    */
   enum SpiMasterSlave : uint32_t {
      SpiMasterSlave_Slave    = SPI_MCR_MSTR(0),  ///< Operate as Master
      SpiMasterSlave_Master   = SPI_MCR_MSTR(1),  ///< Operate as Slave
   };

   /**
    * Continuous SCK Enable
    * (spi_mcr_cont_scke)
    *
    * Whether the Serial Communication Clock (SCK) runs continuously
    */
   enum SpiContinuousClock : uint32_t {
      SpiContinuousClock_Disable   = SPI_MCR_CONT_SCKE(0),  ///< Clock during transfers only
      SpiContinuousClock_Enable    = SPI_MCR_CONT_SCKE(1),  ///< Continuous clock
   };

   /**
    * Controls SPI operation while in debug mode
    * (spi_mcr_frz)
    *
    * Enable transfers to be stopped on the next frame boundary when the device enters Debug mode.
    */
   enum SpiFreeze : uint32_t {
      SpiFreeze_Disabled   = SPI_MCR_FRZ(0),  ///< Continue in debug
      SpiFreeze_Enabled    = SPI_MCR_FRZ(1),  ///< Suspend in debug
   };

   /**
    * Enables Doze mode (when processor is waiting?)
    * (spi_mcr_doze)
    *
    * Controls the module operation in dose mode
    */
   enum SpiDoze : uint32_t {
      SpiDoze_Disabled   = SPI_MCR_DOZE(0),  ///< Ignore doze
      SpiDoze_Enabled    = SPI_MCR_DOZE(1),  ///< Suspend in doze
   };

   /**
    * Modified Timing Format
    * (spi_mcr_mtfe)
    *
    * Controls when the module master samples serial-in,
    * This field is only valid when CPHA bit 0.
    */
   enum SpiModifiedTiming {
      SpiModifiedTiming_Normal     = SPI_MCR_MTFE(0)|SPI_MCR_SMPL_PT(0),  ///< Normal Timing
      SpiModifiedTiming_0_Clocks   = SPI_MCR_MTFE(1)|SPI_MCR_SMPL_PT(0),  ///< No delay from SCK edge to SIN sample
      SpiModifiedTiming_1_Clocks   = SPI_MCR_MTFE(1)|SPI_MCR_SMPL_PT(1),  ///< 1 clock  from SCK edge to SIN sample
      SpiModifiedTiming_2_Clocks   = SPI_MCR_MTFE(1)|SPI_MCR_SMPL_PT(2),  ///< 2 clocks from SCK edge to SIN sample
   };

   /**
    * Clear selected FIFOs
    * (spi_mcr_clr_fifox)
    *
    * Selectively clear transmit or receive FIFOs
    */
   enum SpiClearFifo {
      SpiClearFifo_None   = SPI_MCR_CLR_TXF(0)|SPI_MCR_CLR_RXF(0),  ///< FIFOs not affected
      SpiClearFifo_Rx     = SPI_MCR_CLR_TXF(0)|SPI_MCR_CLR_RXF(1),  ///< Clear Rx FIFO
      SpiClearFifo_Tx     = SPI_MCR_CLR_TXF(1)|SPI_MCR_CLR_RXF(0),  ///< Clear Tx FIFO
      SpiClearFifo_Both   = SPI_MCR_CLR_TXF(1)|SPI_MCR_CLR_RXF(1),  ///< Clear Rx & Tx FIFOs
   };

   /**
    * Handling of Rx Overflow Data
    * (spi_mcr_rooe)
    *
    * Discard incoming data or overwite previous data on RxFIFO overflow
    */
   enum SpiRxOverflowHandling : uint32_t {
      SpiRxOverflowHandling_Ignore      = SPI_MCR_ROOE(0),  ///< Ignore incoming
      SpiRxOverflowHandling_Overwrite   = SPI_MCR_ROOE(1),  ///< Overwrite existing
   };

   /**
    * Module Disable
    * (spi_mcr_mdis)
    *
    * Allows the clock to be stopped to the non-memory mapped logic of the SPI
    * effectively putting the SPI in a software-controlled power-saving state
    */
   enum SpiClock : uint32_t {
      SpiClock_Enabled    = SPI_MCR_MDIS(0),  ///< Enabled
      SpiClock_Disabled   = SPI_MCR_MDIS(1),  ///< Disabled
   };

   /**
    * Enable selected FIFOs
    * (spi_mcr_dis_fifox)
    *
    * Selectively enable transmit or receive FIFOs
    */
   enum SpiEnableFifo {
      SpiEnableFifo_Both   = SPI_MCR_DIS_TXF(0)|SPI_MCR_DIS_RXF(0),  ///< Enable Rx & Tx FIFOs
      SpiEnableFifo_Tx     = SPI_MCR_DIS_TXF(0)|SPI_MCR_DIS_RXF(1),  ///< Enable Tx FIFO
      SpiEnableFifo_Rx     = SPI_MCR_DIS_TXF(1)|SPI_MCR_DIS_RXF(0),  ///< Enable Rx FIFO
      SpiEnableFifo_None   = SPI_MCR_DIS_TXF(1)|SPI_MCR_DIS_RXF(1),  ///< Disable Rx & Tx FIFOs
   };

   /**
    * Halt
    * (spi_mcr_halt)
    *
    * Starts and stops SPI transfers
    */
   enum SpiHalt : uint32_t {
      SpiHalt_StartTransfers   = SPI_MCR_HALT(0),  ///< Start transfers
      SpiHalt_StopTransfers    = SPI_MCR_HALT(1),  ///< Stop transfers
   };

   /**
    * Mode
    * (spi_ctar_mode[0])
    *
    * Communication mode
    * 0: Active-high clock (idles low), Data is captured on leading edge of SCK and changes on the following edge.
    * 1: Active-high clock (idles low), Data changes on leading edge of SCK and is captured on the following edge.
    * 2: Active-low clock (idles high), Data is captured on leading edge of SCK and changes on the following edge.
    * 3: Active-low clock (idles high), Data changes on leading edge of SCK and is captured on the following edge.
    */
   enum SpiMode {
      SpiMode_0   = SPI_CTAR_CPOL(0)|SPI_CTAR_CPHA(0),  ///< Mode 0: CPOL=0, CPHA=0
      SpiMode_1   = SPI_CTAR_CPOL(0)|SPI_CTAR_CPHA(1),  ///< Mode 1: CPOL=0, CPHA=1
      SpiMode_2   = SPI_CTAR_CPOL(1)|SPI_CTAR_CPHA(0),  ///< Mode 2: CPOL=1, CPHA=0
      SpiMode_3   = SPI_CTAR_CPOL(1)|SPI_CTAR_CPHA(1),  ///< Mode 3: CPOL=1, CPHA=1
   };

   /**
    * SPI Frame sizes
    * (spi_ctar_fmsz[0])
    *
    * Transfers are from 4 to 16 bits in size
    */
   enum SpiFrameSize {
      SpiFrameSize_4_bits    = SPI_CTAR_FMSZ(4-1),   ///< 4 bits/transfer
      SpiFrameSize_5_bits    = SPI_CTAR_FMSZ(5-1),   ///< 5 bits/transfer
      SpiFrameSize_6_bits    = SPI_CTAR_FMSZ(6-1),   ///< 6 bits/transfer
      SpiFrameSize_7_bits    = SPI_CTAR_FMSZ(7-1),   ///< 7 bits/transfer
      SpiFrameSize_8_bits    = SPI_CTAR_FMSZ(8-1),   ///< 8 bits/transfer
      SpiFrameSize_9_bits    = SPI_CTAR_FMSZ(9-1),   ///< 9 bits/transfer
      SpiFrameSize_10_bits   = SPI_CTAR_FMSZ(10-1),  ///< 10 bits/transfer
      SpiFrameSize_11_bits   = SPI_CTAR_FMSZ(11-1),  ///< 11 bits/transfer
      SpiFrameSize_12_bits   = SPI_CTAR_FMSZ(12-1),  ///< 12 bits/transfer
      SpiFrameSize_13_bits   = SPI_CTAR_FMSZ(13-1),  ///< 13 bits/transfer
      SpiFrameSize_14_bits   = SPI_CTAR_FMSZ(14-1),  ///< 14 bits/transfer
      SpiFrameSize_15_bits   = SPI_CTAR_FMSZ(15-1),  ///< 15 bits/transfer
      SpiFrameSize_16_bits   = SPI_CTAR_FMSZ(16-1),  ///< 16 bits/transfer
   };

   /**
    * Transmission order
    * (spi_ctar_lsbfe[0])
    *
    * Transmission order
    */
   enum SpiBitOrder {
      SpiBitOrder_MsbFirst   = SPI_CTAR_LSBFE(0),  ///< MSB sent first
      SpiBitOrder_LsbFirst   = SPI_CTAR_LSBFE(1),  ///< LSB sent first
   };

   /**
    * CTAR Selection
    * (spi_ctar_sel)
    *
    * Selects between available CTAR registers
    */
   enum SpiCtarSelect : uint8_t {
      SpiCtarSelect_0   = 0,  ///< CTAR 0
      SpiCtarSelect_1   = 1,  ///< CTAR 1
   };

   /**
    * Behaviour of peripheral select signals between transfers/transactions
    * (PeripheralSelectMode)
    *
    * Select whether Peripheral Select is returned to idle between transfers or transactions
    */
   enum SpiPeripheralSelectMode : uint8_t {
      SpiPeripheralSelectMode_Transfer      = (0),  ///< Asserted for each transfer within transaction
      SpiPeripheralSelectMode_Transaction   = (1),  ///< Asserted for entire transaction
      SpiPeripheralSelectMode_Continuous    = (2),  ///< Asserted until another device is selected
   };

   /**
    * Assert PCS between transfers
    * (spi_pushr_cont)
    *
    * Select whether Peripheral Select is returned to idle between transfers
    */
   enum SpiSelectMode : uint32_t {
      SpiSelectMode_Idle         = SPI_PUSHR_CONT(0),  ///< Idle between transfers
      SpiSelectMode_Continuous   = SPI_PUSHR_CONT(1),  ///< Asserted between transfers
   };

   /**
    * CTAR selection for frame within DMA data buffer
    * (spi_pushr_ctas)
    *
    * Selects which CTAR is used to specify the transfer attributes for a SPI frame
    */
   enum SpiCtar : uint32_t {
      SpiCtar_Dma   = SPI_PUSHR_CTAS(1),  ///< CTAR for DMA
   };

   /**
    * End Of Queue for frame within DMA data buffer
    * (spi_pushr_eoq)
    *
    * Indicates to the SPI that the current transfer is the last in a queue
    * At the end of the transfer, the EOQF bit in the SR is set
    */
   enum SpiEndOfQueue {
      SpiEndOfQueue_Assert   = SPI_PUSHR_EOQ(1),  ///< Is end-of-queue
   };

   /**
    * Clear Transfer Counter for frame within DMA data buffer
    * (spi_pushr_ctcnt)
    *
    * Clears the TCNT field in the TCR register. 
    * The TCNT field is cleared before the SPI starts transmitting the current SPI frame.
    * The counter increments every time the last bit of an SPI frame is transmitted
    */
   enum SpiCountAction {
      SpiCountAction_Clear   = SPI_PUSHR_CTCNT(1),  ///< Clear counter
   };

   /**
    * Peripheral Chip Select
    * (spi_pushr_pcs_enum)
    *
    * Mask to select which Peripheral Chip Select Line (PCS) to assert during transaction
    * Note: more than one PCS may be asserted (allows use of an external decoder)
    */
   enum SpiPeripheralSelect : uint32_t {
      SpiPeripheralSelect_Pcs0   = SPI_PUSHR_PCS(1U<<0),  ///< Assert PCS0 during transaction
      SpiPeripheralSelect_Pcs1   = SPI_PUSHR_PCS(1U<<1),  ///< Assert PCS1 during transaction
      SpiPeripheralSelect_Pcs2   = SPI_PUSHR_PCS(1U<<2),  ///< Assert PCS2 during transaction
      SpiPeripheralSelect_Pcs3   = SPI_PUSHR_PCS(1U<<3),  ///< Assert PCS3 during transaction
      SpiPeripheralSelect_Pcs4   = SPI_PUSHR_PCS(1U<<4),  ///< Assert PCS4 during transaction
      SpiPeripheralSelect_None   = SPI_PUSHR_PCS(0),      ///< PCSx not asserted
   };

   /**
    * Combines two SpiPeripheralSelect values (by ORing)
    * Used to create a combined SpiPeripheralSelect mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return  Combined value
    */
   constexpr SpiPeripheralSelect operator|(SpiPeripheralSelect left, SpiPeripheralSelect right) {
      return SpiPeripheralSelect(uint32_t(left)|uint32_t(right));
   }
   
   /**
    * Combines two SpiPeripheralSelect values (by ANDing) to produce a bool result
    * Used to check a value against a SpiPeripheralSelect mask
    * 
    * @param left    Left operand
    * @param right   Right operand
    * 
    * @return boolean value indicating if the result is non-zero
    */
   constexpr bool operator&(SpiPeripheralSelect left, SpiPeripheralSelect right) {
      return bool(uint32_t(left)&uint32_t(right));
   }
   

   // Bit operators for CTAR register fields
   constexpr inline uint32_t operator|(SpiMode op1, SpiBitOrder op2)     { return uint32_t(op1)|uint32_t(op2); };
   constexpr inline uint32_t operator|(SpiBitOrder op1, SpiMode op2)     { return uint32_t(op1)|uint32_t(op2); };
   
class SpiBasicInfo {

public:

   /**
    * Class used to do initialisation of communication parameters (CTAR) in SPI
    *
    * This class has a templated constructor that accepts various values:
    *
    * @note This constructor may be used to create a const instance in ROM
    *
    * Example:
    * @code
    * // Initialisation values for Spi0
    * // Options available vary with device - See Spi0::DefaultInitValue for example
    * static const Spi0::SerialInit serialInit {
    *
    *    // Omitted parameters are take to be zero unless a base value is given
    *
    *    1_MHz ,                 // Speed of interface
    *    SpiMode_o ,             // Mode - Mode 0: CPOL=0, CPHA=0
    *    SpiFrameSize_8_bits ,   // SPI Frame sizes - 8 bits/transfer
    *    SpiBitOrder_LsbFirst,   // Transmission order - LSB sent first
    *
    *    // Optional base value to start with (must be last parameter)
    *    Spi1::DefaultSerialInitValue,
    * };
    *
    * // Initialise SPI from values specified above
    * Spi0::configure(serialInit);
    * @endcode
    */
   class SerialInit {
   
   public:
      /**
       * Copy Constructor
       */
      constexpr SerialInit(const SerialInit &other) = default;
      /**
       * Assignment operator
       */
      constexpr SerialInit& operator=(const SerialInit& t) = default;
   
      /**
       * Default Constructor
       */
      constexpr SerialInit() = default;
   
      ///  Clock and Transfer Attributes Register
      Ctar ctar = 0;

      ///  Module Configuration Register
      uint32_t speed = 0_Hz;

      /**
       * Constructor for Mode
       * (spi_ctar_mode)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiMode Communication mode
       *        0: Active-high clock (idles low), Data is captured on leading edge of SCK and changes on the following edge.
       *        1: Active-high clock (idles low), Data changes on leading edge of SCK and is captured on the following edge.
       *        2: Active-low clock (idles high), Data is captured on leading edge of SCK and changes on the following edge.
       *        3: Active-low clock (idles high), Data changes on leading edge of SCK and is captured on the following edge.
       */
      template <typename... Types>
      constexpr SerialInit(SpiMode spiMode, Types... rest) : SerialInit(rest...) {
   
         ctar.value = (ctar.value&~(SPI_CTAR_CPOL_MASK|SPI_CTAR_CPHA_MASK)) | spiMode;
      }
   
      /**
       * Constructor for SPI Frame sizes
       * (spi_ctar_fmsz)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiFrameSize Transfers are from 4 to 16 bits in size
       */
      template <typename... Types>
      constexpr SerialInit(SpiFrameSize spiFrameSize, Types... rest) : SerialInit(rest...) {
   
         ctar.value = (ctar.value&~SPI_CTAR_FMSZ_MASK) | spiFrameSize;
      }
   
      /**
       * Constructor for Transmission order
       * (spi_ctar_lsbfe)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiBitOrder Transmission order
       */
      template <typename... Types>
      constexpr SerialInit(SpiBitOrder spiBitOrder, Types... rest) : SerialInit(rest...) {
   
         ctar.value = (ctar.value&~SPI_CTAR_LSBFE_MASK) | spiBitOrder;
      }
   
      /**
       * Constructor for Speed of interface
       * (speed)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param hertz Speed of transmission
       */
      template <typename... Types>
      constexpr SerialInit(const Hertz& hertz, Types... rest) : SerialInit(rest...) {
   
         speed = hertz;
      }
   
   }; // class SerialInit
   
   /**
    * Class used to hold a calculated configuration that may be reused to avoid calculation overhead
    */
   class SpiCalculatedConfiguration {
   
   public:
      /**
       * Copy Constructor
       */
      constexpr SpiCalculatedConfiguration(const SpiCalculatedConfiguration &other) = default;
   
      PushrCommand pushrCommand       = 0;   //!<  PUSHR.COMMAND register value for most transfer
      PushrCommand pushrFinalCommand  = 0;   //!<  PUSHR.COMMAND register value for final transfer
      Ctar         ctar               = 0;   //!<  CTAR register value e.g. Baud, number of bits, timing
   
      /**
       * Default Constructor
       */
      constexpr SpiCalculatedConfiguration() = default;
   
      /**
       * Constructor
       *
       * @param pushrCommand        Modifier for PUSH register value within transaction
       * @param pushrFinalCommand   Modifier for final PUSH register value in a transaction
       * @param ctar                CTAR value (Communication settings)
       *
       * @note This constructor may be used to create a const instance in ROM
       */
      constexpr SpiCalculatedConfiguration(uint16_t pushrCommand, uint16_t pushrFinalCommand, uint32_t ctar) :
         pushrCommand(pushrCommand),
         pushrFinalCommand(pushrFinalCommand),
         ctar(ctar) {
      }
   
      uint32_t firstValue(uint16_t data) const {
         return (pushrCommand.value<<16)|data|SpiCountAction_Clear;
      }
      uint32_t middleValue(uint16_t data) const {
         return (pushrCommand.value<<16)|data;
      }
      uint32_t lastValue(uint16_t data) const {
         return (pushrFinalCommand.value<<16)|data|SpiEndOfQueue_Assert;
      }
   
      /**
       * Set SPI Frame size
       * (spi_ctar_fmsz)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiFrameSize Transfers are from 4 to 16 bits in size
       */
      void setFrameSize(SpiFrameSize spiFrameSize) {
   
         ctar.value = (ctar.value&~SPI_CTAR_FMSZ_MASK) | spiFrameSize;
      }
   
   }; // class SpiCalculatedConfiguration

   
      /**
       * Constructor for Active-low PCSx
       * By default PCSx signals are active-high i.e. they are high to indicate a transfers/transactions
       * This constructor changes the given PCSx to active-low i.e. PCSx will go low for transfer
       * (spi_mcr_pcsis_enum)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiPcsActiveLow PCS signal to be made Active-low
       *                         SpiPcsActiveLow_None clears all selections
       *                         SpiPcsActiveLow_PCSn values are cumulative
       */
      template <typename... Types>
      constexpr Init(SpiPcsActiveLow spiPcsActiveLow, Types... rest) : Init(rest...) {
   
         if (spiPcsActiveLow == SpiPcsActiveLow_None) {
            mcr.value &= ~SPI_MCR_PCSIS_MASK;
         }
         else {
            mcr.value |= spiPcsActiveLow;
         }
      }
   
      /**
       * Constructor for initial Peripheral selection
       * (spi_pushr_pcs_enum)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiPeripheralSelect PCS signal to assert during transfers
       *                SpiPeripheralSelect_None clears all selections
       *                SpiPeripheralSelect_XXXX values are cumulative
       */
      template <typename... Types>
      constexpr Init(SpiPeripheralSelect spiPeripheralSelect, Types... rest) : Init(rest...) {
   
         if (spiPeripheralSelect == SpiPeripheralSelect_None) {
            pushr.value      &= ~SPI_PUSHR_PCS_MASK;
            pushrFinal.value &= ~SPI_PUSHR_PCS_MASK;
         }
         else {
            pushr.value      |= spiPeripheralSelect;
            pushrFinal.value |= spiPeripheralSelect;
         }
      }
   
      /**
       * Constructor for initial CTAR selection
       * (spi_ctar_sel)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiCtarSelect CTAR to use during transfers
       */
      template <typename... Types>
      constexpr Init(SpiCtarSelect spiCtarSelect, Types... rest) : Init(rest...) {
   
         pushr.value      = (pushr.value      & ~SPI_PUSHR_CTAS_MASK)|SPI_PUSHR_CTAS(spiCtarSelect);
         pushrFinal.value = (pushrFinal.value & ~SPI_PUSHR_CTAS_MASK)|SPI_PUSHR_CTAS(spiCtarSelect);
      }
   
      /**
       * Constructor for initial Peripheral selection timing
       * (PeripheralSelectMode)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param spiPeripheralSelectMode Behaviour of peripheral select signals between transfers/transactions
       */
      template <typename... Types>
      constexpr Init(SpiPeripheralSelectMode spiPeripheralSelectMode, Types... rest) : Init(rest...) {
   
         pushr.value      |= (spiPeripheralSelectMode>=1)?SPI_PUSHR_CONT_MASK:0;
         pushrFinal.value |= (spiPeripheralSelectMode>=2)?SPI_PUSHR_CONT_MASK:0;
      }
   
}; // class SpiBasicInfo 

class Spi0Info : public SpiBasicInfo {

public:

   //! Number of signals available in info table
   static constexpr int numSignals  = 8;

   //! Information for each signal of peripheral
   static constexpr PinInfo  info[] = {

         //      Signal                 Pin                                  PinIndex                PCR value
         /*   0: SPI0_SCK             = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   1: SPI0_SIN             = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   2: SPI0_SOUT            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   3: SPI0_PCS0            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   4: SPI0_PCS1            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   5: SPI0_PCS2            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   6: SPI0_PCS3            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   7: SPI0_PCS4            = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
   };

   /**
    * Initialise pins used by peripheral
    *
    * @note Only the lower 16-bits of the PCR registers are affected
    */
   static void initPCRs() {
   }

   /**
    * Release pins used by peripheral
    *
    * @note Only the lower 16-bits of the PCR registers are affected
    */
   static void clearPCRs() {
   }

   /*
    * Template:spi0_mk_pcsis6
    */
   //! Map all allocated pins on a peripheral when enabled
   static constexpr bool mapPinsOnEnable = false;


   
   /**
    * Configures all mapped pins associated with SPI0
    *
    * @note Locked pins will be unaffected
    */
   static void configureAllPins() {
   
      // Configure pins if selected and not already locked
      if constexpr (mapPinsOnEnable) {
         initPCRs();
      }
   }
   
   /**
    * Disabled all mapped pins associated with SPI0
    *
    * @note Only the lower 16-bits of the PCR registers are modified
    *
    * @note Locked pins will be unaffected
    */
   static void disableAllPins() {
   
      // Disable pins if selected and not already locked
      if constexpr (mapPinsOnEnable) {
         clearPCRs();
      }
   }
   
   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = SPI0_IRQS;
   
   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = sizeofArray(irqNums);
   
   /**
    * Enable interrupts in NVIC
    */
   static void enableNvicInterrupts() {
      NVIC_EnableIRQ(irqNums[0]);
   }
   
   /**
    * Enable and set priority of interrupts in NVIC
    * Any pending NVIC interrupts are first cleared.
    *
    * @param[in]  nvicPriority  Interrupt priority
    */
   static void enableNvicInterrupts(NvicPriority nvicPriority) {
      enableNvicInterrupt(irqNums[0], nvicPriority);
   }
   
   /**
    * Disable interrupts in NVIC
    */
   static void disableNvicInterrupts() {
      NVIC_DisableIRQ(irqNums[0]);
   }
   
   /**
    *  Enable clock to Spi0
    */
   static void enableClock() {
      SIM->SCGC6 = SIM->SCGC6 | SIM_SCGC6_SPI0_MASK;
   }
   
   /**
    *  Disable clock to Spi0
    */
   static void disableClock() {
      SIM->SCGC6 = SIM->SCGC6 & ~SIM_SCGC6_SPI0_MASK;
   }
   
   //! Hardware base address as uint32_t
   static constexpr uint32_t baseAddress = SPI0_BasePtr;
   
   //! Hardware base pointer
   static constexpr HardwarePtr<SPI_Type> spi = baseAddress;
   
   //! Peripheral instance number
   static constexpr unsigned instance = 0;
   
}; // class Spi0Info



#if false
/**
 * Class to handle SPI DMA operations
 * It will create the required buffer to format data for the DMA transfer.
 * This is necessary because of the really stupid SPI transfers that require 32-bit writes to include COMMAND+DATA
 * for each item transferred. Note that some later devices may not require this.
 * This means that to transfer a buffer of data (8/16 bit items) requires copying it to a RAM Buffer up to 4-times its size
 * and add in the command values for each entry.
 *
 * @tparam itemCount Maximum size of buffer that can be expanded (in items)
 */
template<unsigned itemCount>
class SpiDmaHandlerBase {

protected:

   // Maximum number of items in buffer
   static constexpr unsigned MaxItemCount = itemCount;

   // Size of items (always 4 irrespective of actual data size)
   static constexpr unsigned SizeofItems = 4;

   // Expanded buffer with added command values
   union {
      uint32_t bits;
      struct {
         uint16_t data;
         uint16_t command;
      };
   } __attribute__((packed)) expandedBuffer[itemCount];

   // The final Tx value is sent individually to allow different PUSHR value
   uint32_t finalTxValue   = 0;

   // Dummy location for discarding Rx data
   uint32_t discardRxBuffer = 0;

   // Associated SPI
   Spi &spi;

   // Allocated DMA channels - released after transfer completes
   DmaChannelNum dmaTransmitChannel = DmaChannelNum_None;
   DmaChannelNum dmaReceiveChannel  = DmaChannelNum_None;

   /**
    * Constructor
    *
    * @param spi  Associated SPI
    */
   SpiDmaHandlerBase(Spi &spi) : spi(spi) {
   }

public:
   /**
    * Copy-expand data into internal DMA buffer
    * The final value is placed in finalTxValue
    *
    * @tparam T      Type for data (deduced)
    * @tparam N      Size of data array in items (deduced)
    *
    * @param dataIn  Data array to expand
    *
    * @note It is necessary to set the transfer configuration in the SPI before using this
    *       routine as it will make use of information from the SPI to format data.
    */
   template<typename T, unsigned N>
   void loadTxData(const T (&dataIn)[N]) {

      static_assert((sizeof(T) == 1) || (sizeof(T) == 2) , "T must be of size 1 or 2 bytes");
      static_assert(N<=itemCount, "dataIn is too large for buffer allocated");

      // Copy-expand data
      for (unsigned count=0; count<N; count++) {
         expandedBuffer[count].bits = dataIn[count]|spi.pushrMask;
      }
      finalTxValue = dataIn[N-1]|spi.pushrMaskFinal|SPI_PUSHR_EOQ_MASK;
   }

   /**
    * Mark data item in DMA transmit buffer to clear transmit counter.
    *
    * The transmit counter will be cleared before transmission of the associated data.
    * This would usually be set on the first item in the buffer.
    *
    * @param index   Index in transfer
    * @param data    Data to write
    *
    * @note It is necessary to set the transfer configuration in the SPI before using this
    *       routine as it will make use of information from the SPI to format data.
    */
   void markDataToClearCounter(unsigned index=0) {

      usbdm_assert(index<MaxItemCount, "Array index error");

      expandedBuffer[index].bits |= SPI_PUSHR_COMMAND_CTCNT_MASK;
   }

   /**
    * Mark data item in DMA transmit buffer as end-of-queue.
    *
    * Indicates the associated data value is End of Queue, the transmit and
    * receive operations will be disabled after this item completes transmission
    * This should only be set on the last item in the buffer.
    *
    * @param index   Index in transfer
    * @param data    Data to write
    *
    * @note It is necessary to set the transfer configuration in the SPI before using this
    *       routine as it will make use of information from the SPI to format data.
    */
   void markDataAsEoq(unsigned index) {

      usbdm_assert(index<MaxItemCount, "Array index error");

      expandedBuffer[index].bits |= SPI_PUSHR_EOQ_MASK;
   }

   ErrorCode allocateDmaChannels() {

      // deallocate any channels in use
      cleanUp();

      // Allocate DMA channel to use for transmission
      dmaTransmitChannel = Dma0::allocateChannel();
      if (dmaTransmitChannel == DmaChannelNum_None) {
         return setErrorCode(E_NO_RESOURCE);
      }

      // Allocate DMA channel to use for reception
      dmaReceiveChannel = Dma0::allocateChannel();
      if (dmaReceiveChannel == DmaChannelNum_None) {
         // Release successfully allocated channel as we can't use it now
         Dma0::freeChannel(dmaTransmitChannel);
         return setErrorCode(E_NO_RESOURCE);
      }
      return E_NO_ERROR;
   }

   /**
    * This TCD is chained from the main Tx TCD and
    * allows the last value transferred to have a individual PUSHR value
    */
   DmaTcd __attribute__((aligned(32)))  finalTcd = DmaTcd (
      {  /* Source */
         /* Address                  */ 0,                                           // Source address (filled in)
         /* Offset                   */ 0,                                           // Source address doesn't change
         /* Size                     */ DmaSize_32bit,                               // 32-bit read from source address
      },
      {  /* Destination */
         /* Address                  */ 0,                                           // Destination address (filled in)
         /* Offset                   */ 0,                                           // Destination address doesn't change
         /* Size                     */ DmaSize_32bit,                               // 32-bit write to destination address
      },
      /* Minor loop byte count    */ sizeof(uint32_t),                               // Total transfer in one minor-loop
      /* Major loop count         */ 1,                                              // Transfer single item

      {  // CSR
         /* Disable Req. on complete */ DmaStopOnComplete_Enabled,                   // Clear hardware request when major loop completed
         /* IRQ on major complete    */ DmaIntMajor_Enabled,                         // Interrupt
      }
   );

   /*
    * Initialises the final Tx transfer to SPI.
    * This sets up a TCD that is chained from the main Tx TCD
    * and allows the last value transferred to have a individual PUSHR
    */
   ErrorCode initialiseFinalTransfer() {
      finalTcd.SADDR = (uint32_t)&finalTxValue;
      finalTcd.DADDR = (uint32_t)spi.spi+offsetof(SPI_Type, PUSHR);

      return E_NO_ERROR;
   }

   /**
    * Set up for DMA operation
    * - Configure DMA Mux for Tx channel
    * - Configures DMA TCD for Tx
    * No transfers are actually started
    *
    * @param numElements         Number of elements to transfer
    * @param advanceReadAddress  Whether to advance DMA read pointer during transfer
    *
    * @note This method may be called before the SPI configuration has been set.
    *
    * @return E_NOERROR on success
    * @return E_NO_RESOURCE if failed to allocate required DMA channels
    */
   ErrorCode initialiseTxDma(unsigned numElements, bool advanceReadAddress) {

      int32_t   offset          = advanceReadAddress?0:SizeofItems;
      uint32_t  spiPushrAddress = spi.spi+offsetof(SPI_Type, PUSHR);
      /**
       * Structure to define the Transmit DMA transfer
       *
       * Note: This uses a 32-bit transfer even though the transmit data may only be 8 or 16-bit
       */
      DmaTcd txTcd = DmaTcd (
         {  /* Source */
            /* Address                  */ (uint32_t)(expandedBuffer),  // Source is array
            /* Offset                   */ offset,                      // Source address advances 0/1 element per request
            /* Size                     */ DmaSize_32bit,               // 32-bit read from source address
         },
         {  /* Destination */
            /* Address                  */ spiPushrAddress,             // Destination is SPI.PUSHR data register
            /* Offset                   */ 0,                           // Destination address doesn't change
            /* Size                     */ DmaSize_32bit,               // 32-bit write to destination address
            /* ScatterGather address    */ (int32_t) &finalTcd,         // Chain to finalTcd
         },
         /* Minor loop byte count       */ dmaNBytes(SizeofItems),      // Total transfer in one minor-loop
         /* Major loop count            */ dmaCiter(numElements-1),     // Transfer entire buffer

         {  // CSR
           /* Scatter/Gather enable     */ DmaScatterGather_Enabled     // Chain to finalTcd
         }
      );

      // Connect DMA channel to SPI Tx
      DmaMux0::configure(dmaTransmitChannel, Dma0Slot_SPI0_Tx, DmaMuxEnable_Continuous);

      // Configure the Tx transfer
      Dma0::configureTransfer(dmaTransmitChannel, txTcd);

      return E_NO_ERROR;
   }

   /**
    * Set up for DMA operation
    * - Configure DMA Mux for Rx channels
    * - Configures DMA TCD for Rx
    * No transfers are actually started
    *
    * @param rxBuffer     Buffer for received data (may be null)
    * @param rxDataSize   Size of elements in rxBuffer (either 1 or 2 bytes)
    * @param numElements  Number of elements in rxBuffer
    *
    * @note This method may be called before the SPI configuration has been set.
    *
    * @return E_NOERROR on success
    * @return E_NO_RESOURCE if failed to allocate required DMA channels
    */
   ErrorCode initialiseRxDma(void *rxBuffer, unsigned rxDataSize, unsigned numElements) {

      // Size for Rx data DMA transfers
      DmaSize   rxDmaSize      = (rxDataSize==1)?DmaSize_8bit:DmaSize_16bit;
      uint32_t  spiPoprAddress = spi.spi+offsetof(SPI_Type, POPR);

      int32_t writeOffset = rxDataSize;
      if (rxBuffer==nullptr) {
         writeOffset = 0;
         rxBuffer = &discardRxBuffer;
      }

      /**
       * Structure to define the Receive DMA transfer
       *
       * Note: The transfer size used here is 8 or 16-bits only
       */
      DmaTcd rxTcd (
         {  /* Source */
            /* Address                  */ spiPoprAddress,            // Source is SPI.POPR data register
            /* Offset                   */ 0,                         // Source address doesn't change
            /* Size                     */ rxDmaSize,                 // Read from source address depends on data size
            /* Last address adjustment  */ 0,                         // Source address doesn't change
         },
         {  /* Destination */
            /* Address                  */ (uint32_t)(rxBuffer),      // Destination array
            /* Offset                   */ writeOffset,               // Destination address advances 1 element for each request
            /* Size                     */ rxDmaSize,                 // Write to destination address depends on data size
            /* Last address adjustment  */ 0,                         // Don't adjust destination address
         },
         /* Minor loop byte count       */ dmaNBytes(rxDataSize),     // Total transfer in one minor-loop
         /* Major loop count            */ dmaCiter(numElements),     // Transfer entire buffer

         {  // CSR
            /* Disable Req. on complete */ DmaStopOnComplete_Enabled, // Clear hardware request when major loop completed
            /* IRQ on major complete    */ DmaIntMajor_Enabled,       // Generate interrupt on completion of major-loop
         }
      );

      // Connect DMA channel to SPI Rx
      DmaMux0::configure(dmaReceiveChannel, Dma0Slot_SPI0_Rx, DmaMuxEnable_Continuous);

      // Configure the Rx transfer
      Dma0::configureTransfer(dmaReceiveChannel, rxTcd);

      return E_NO_ERROR;
   }

   /**
    * Set up for DMA operation
    * - Allocates DMA channels
    * - Configure DMA Mux for Tx and Rx channels
    * - Configures DMA channels for Tx and Rx
    * No transfers are actually started
    *
    * @tparam T  Type of elements in rxBuffer (deduced)
    * @tparam N  Number of elements in rxBuffer (deduced)
    *            This becomes the number of elements to Tx and Rx
    *
    * @param rxBuffer Buffer for received data
    *
    * @note This method may be called before the SPI configuration has been set.
    *
    * @return E_NOERROR on success
    * @return E_NO_RESOURCE if failed to allocate required DMA channels
    */
   template<typename T, unsigned N>
   ErrorCode initialiseDma(const T (&rxBuffer)[N]) {

      static_assert((sizeof(T) == 1) || (sizeof(T) == 2) , "T must be of size 1 or 2 bytes");
      ErrorCode rc;
      do {
         rc = allocateDmaChannels();
         if (rc != E_NO_ERROR) {
            break;
         }
         rc = initialiseTxDma(N, false);
         if (rc != E_NO_ERROR) {
            break;
         }
         rc = initialiseFinalTransfer();
         if (rc != E_NO_ERROR) {
            break;
         }
         rc = initialiseRxDma((void*)rxBuffer, sizeof(T), N);
         if (rc != E_NO_ERROR) {
            break;
         }
      } while(false);
      return rc;
   }

   /**
    * Set up for DMA operation
    * - Copies Tx data to internal buffer (with expansion)
    * - Allocates DMA channels
    * - Configure DMA Mux for Tx and Rx channels
    * - Configures DMA channels for Tx and Rx
    * No transfers are actually started
    *
    * @tparam T         Type for data (deduced)
    * @tparam N         Number of data items in transfer
    * @param dataIn     Data to send to SPI
    * @param rxBuffer   Buffer for received data
    *
    * @return E_NOERROR on success
    */
   template<typename T, unsigned N>
   ErrorCode initialiseTxRx(const T (&dataIn)[N], T (&rxBuffer)[N]) {

      // Set up transmit buffer
      loadTxData(dataIn);

      // Set up DMA
      return initialiseDma(rxBuffer);
   }

   /**
    * Start DMA transfers To/From SPI
    */
   void startTransfer() {

      // Clear SPI Status
      spi.getStatus();

      spi.configureInterrupts(
            SpiTxCompleteInterrupt_Enabled,
            SpiEndOfQueueInterrupt_Enabled,
            SpiTxFifoUnderflowInterrupt_Enabled,
            SpiRxFifoOverflowInterrupt_Enabled);

      spi.clearFifos(SpiClearFifo_Both);

      spi.configureFifoRequests(SpiTxFifoRequest_Dma, SpiRxFifoRequest_Dma);

      spi.enableTransfer();

      Dma0::enableMultipleErrorInterrupts((1<<dmaTransmitChannel)|(1<<dmaReceiveChannel), true);

      // Enable Rx hardware requests
      Dma0::enableRequests(dmaReceiveChannel);

      // Enable Tx hardware requests
      Dma0::enableRequests(dmaTransmitChannel);
   }

protected:
   static void cleanUp(DmaChannelNum &channel) {

      if (channel == DmaChannelNum_None) {
         return;
      }
      // Clear request and release DMA channel
      Dma0::enableRequests(channel, false);
      DmaMux0::disable(channel);
      Dma0::setCallback(channel, nullptr);
      Dma0::freeChannel(channel);
      channel = DmaChannelNum_None;
   }

public:
   void cleanUp() {
      cleanUp(dmaTransmitChannel);
      cleanUp(dmaReceiveChannel);
   }
};

#endif

#if false

/**
 * @brief Template class representing a SPI interface
 *
 * @tparam  Info           Class describing Spi hardware
 */
template<class Info>
class SpiBase_T : public Spi, public Info {

public:

   static unsigned dmaComplete;
   static uint32_t dmaErrorCode;
   static bool     keepDmaConfiguration;

   /**
    * Class to handle SPI DMA operations
    * It will create the required buffer to format data for the DMA transfer.
    * This is necessary because of the really stupid SPI transfers that require 32-bit writes to include COMMAND+DATA
    * for each item transferred. Note that some later devices may not require this.
    * This means that to transfer a buffer of data (8/16 bit items) requires copying it to a RAM Buffer up to 4-times its size
    * and add in the command values for each entry.
    *
    * @tparam itemCount Maximum size of buffer that can be expanded (in items)
    */
   template<unsigned itemCount>
   class SpiDmaHandler_T : public SpiDmaHandlerBase<itemCount> {

   private:
      using Super = SpiDmaHandlerBase<itemCount>;

      /**
       * DMA complete callback
       *
       * Sets flag to indicate sequence complete.
       */
      static void dmaCallback(DmaChannelNum channel, uint32_t errorStatus) {

         Dma0::clearInterruptRequest(channel);
         Dma0::enableRequests(channel, false);
         if (dmaComplete>0) {
            dmaComplete--;
         }
         if (errorStatus&DMA_ES_VLD_MASK) {
            // Error callback
            dmaErrorCode = errorStatus;
            dmaComplete = 0;
         }
      }

      /**
       * SPI callback
       *
       * Used for debug timing checks.
       * LED toggles on each SPI event
       *
       * @param status Interrupt status value from SPI->SR
       */
      static void spiCallback(uint32_t status) {
         (void)status;
      }

   public:
      SpiDmaHandler_T(Spi &spi) : Super(spi) {
         spi.setCallback(spiCallback);
      }

      /**
       * Start transfer
       */
      void startTransfer() {

         dmaComplete = 2;

         // Set up DMA IRQ handlers
         Dma0::setCallback(Super::dmaTransmitChannel, dmaCallback);
         Dma0::setCallback(Super::dmaReceiveChannel,  dmaCallback);

         Dma0::enableNvicInterrupts(Super::dmaTransmitChannel, NvicPriority_Normal);
         Dma0::enableNvicInterrupts(Super::dmaReceiveChannel,  NvicPriority_Normal);
         Dma0::enableNvicErrorInterrupt(NvicPriority_MidHigh);
         Super::startTransfer();
      }

      bool isBusy() {
         if (errorCode != 0) {
            // Release resources on error
            Super::cleanUp();
         }
         if ((dmaComplete == 0) && !keepDmaConfiguration) {
            // Release DMA channels
            Super::cleanUp();
         }
         return dmaComplete != 0;
      }

      /**
       * If set:
       *    - The DMA configuration (including allocated DMA channels) set up by initialiseDma() are
       *      retained for re-use.
       *    - Resources must be manually released by calling cleanUp().
       *
       * If not set:
       *    - Allocated resources are released when the DMA transfer completes successfully
       *
       * @param keepConfiguration  true to keep configuration and resources
       */
      static void setKeepDmaConfiguration(bool keepConfiguration) {
         keepDmaConfiguration = keepConfiguration;
      }

   };

   /**
    * Creates a DMA buffer and associated code for DMA transfers to/from the SPI
    *
    * Examples use:
    * @code
    *    Spi0 spi;
    *
    *    // Configure SPI
    *
    *    constexpr unsigned NumDataItems = 10;
    *
    *    using DataSize = uint16_t; // Can be uint8_t or uint16_t
    *
    *    // Transmit data
    *    DataSize txBuffer[NumDataItems];
    *
    *    // Create DMA buffers etc.
    *    auto txBuffer = spi.createDmaHandler<NumDataItems>();
    *
    *    // Receive buffer
    *    DataSize rxBuffer[NumDataItems];
    *
    *    // Set up DMA transfer from internal buffer -> SPI -> rxBuffer
    *    txBuffer.initialiseDma(rxBuffer);
    *
    *    // Load data into SPI transmit buffer
    *    txBuffer.loadTxData(txBufferOriginal);
    *
    *    // Start transfer
    *    txBuffer.startTransfer();
    *
    *    // Wait for completion
    *    while (txBuffer.isBusy()) {
    *       __asm__("nop");
    *    }
    * @endcode
    *
    * @tparam itemCount Number of items in internal DMA buffer buffer
    *
    * @return Instance of SpiDmaHandler customised for buffer size
    */
   template<unsigned itemCount>
   SpiDmaHandler_T<itemCount> createDmaHandler() {
      return SpiDmaHandler_T<itemCount>(*this);
   }

};
template<class Info>
unsigned SpiBase_T<Info>::dmaComplete = false;

template<class Info>
bool SpiBase_T<Info>::keepDmaConfiguration = false;

template<class Info>
uint32_t SpiBase_T<Info>::dmaErrorCode = 0;
#endif


/**
 * End SPI_Group
 * @}
 */

} // End namespace USBDM
#endif // false // /FTM/_BasicInfoGuard

#endif /* INCLUDE_USBDM_SPI_H_ */
