/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "adc.h"
#include "spi.h"
#include "llwu.h"
#include "control.h"


// User includes
// None

namespace USBDM {

// User declarations
// None

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

// Hardware declarations

/// Battery Level
typedef Adc0::Channel<AdcChannelNum_Se13>                    BatteryLevel;                                 // PTB3(p30)

/// Reset*
typedef PcrTable_T<ControlInfo, 0>                           Resetb;                                       // RESET_b(p26)

/// SWD_CLK
typedef PcrTable_T<ControlInfo, 2>                           SwdClk;                                       // PTA0(p17)

/// SWD_DIO
typedef PcrTable_T<ControlInfo, 7>                           SwdDio;                                       // PTA3(p20)

/// IR Receiver
typedef USBDM::GpioA<4,ActiveHigh>                           IrReceiver;                                   // PTA4(p21)

/// TFT Reset 
typedef USBDM::GpioB<1,ActiveHigh>                           TftResetPin;                                  // PTB1(p28)

/// Charging detection
typedef USBDM::GpioB<0,ActiveHigh>                           Charging;                                     // PTB0(p27)

/// TFT Busy Pin
typedef USBDM::GpioB<2,ActiveHigh>                           TftBusyPin;                                   // PTB2(p29)

/// TFT Backlight
typedef USBDM::GpioC<4,ActiveHigh>                           TftBacklight;                                 // PTC4(p37)

/// Switch 3
typedef USBDM::GpioD<1,ActiveHigh>                           Switch3;                                      // PTD1(p42)

/// Switch 2
typedef USBDM::GpioD<2,ActiveHigh>                           Switch2;                                      // PTD2(p43)

/// Switch 1
typedef USBDM::GpioD<3,ActiveHigh>                           Switch1;                                      // PTD3(p44)

typedef GpioDField<3,0,ActiveHigh>                           Switches;                                     // PTD0(p41), PTD1(p42), PTD2(p43), PTD3(p44)

/// Switch 4
typedef USBDM::GpioD<0,ActiveHigh>                           Switch4;                                      // PTD0(p41)

/// Debug LED
typedef USBDM::GpioD<5,ActiveHigh>                           DebugLed;                                     // PTD5(p46)

/// Touch Panel IRQ
typedef USBDM::GpioD<4,ActiveHigh>                           TouchIrq;                                     // PTD4(p45)

/// Touch Wakeup
typedef Llwu::Pin<LlwuPin_Ptd4>                              TouchWakeup;                                  // PTD4(p45)

/// SPI, Serial Peripheral Interface
typedef Spi0                                                 MySPI;                                        

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
