/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "../Project_Headers/error.h"
#include "../Project_Headers/pin_mapping.h"
#include "../Project_Headers/delay.h"
#include "../Project_Headers/console.h"
#include "../Project_Headers/gpio.h"

#include "../Project_Headers/control.h"
#include "../Project_Headers/gpio.h"
#include "../Project_Headers/llwu.h"
#include "../Project_Headers/pit.h"
#include "../Project_Headers/adc.h"
#include "../Project_Headers/spi.h"


// User includes
// None

namespace USBDM {

// User declarations
// None

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

// Hardware declarations

/// Battery Level
typedef Adc0::Channel<Adc0ChannelNum_Se13>                   BatteryLevel;                                 // PTB3(p30)

/// Reset*
typedef PcrTable_T<ControlInfo, 0>                           Resetb;                                       // RESET_b(p26)

/// SWD_CLK
typedef PcrTable_T<ControlInfo, 2>                           SwdClk;                                       // PTA0(p17)

/// SWD_DIO
typedef PcrTable_T<ControlInfo, 7>                           SwdDio;                                       // PTA3(p20)

/// IR Receiver
typedef USBDM::GpioA<4,ActiveHigh>                           IrReceiver;                                   // PTA4(p21)

/// TFT Reset 
typedef USBDM::GpioB<1,ActiveHigh>                           TftReset;                                     // PTB1(p28)

/// Charging detection
typedef USBDM::GpioB<0,ActiveLow>                            Charging;                                     // PTB0(p27)

/// TFT Backlight
typedef USBDM::GpioC<4,ActiveHigh>                           TftBacklight;                                 // PTC4(p37)

/// Switch 3
typedef USBDM::GpioD<1,ActiveLow>                            Switch3;                                      // PTD1(p42)

/// Switch 2
typedef USBDM::GpioD<2,ActiveLow>                            Switch2;                                      // PTD2(p43)

/// Switch 1
typedef USBDM::GpioD<3,ActiveLow>                            Switch1;                                      // PTD3(p44)

typedef USBDM::GpioDField<3,0,ActiveLow>                     Switches;                                     // PTD0(p41), PTD1(p42), PTD2(p43), PTD3(p44)

/// Switch 4x
typedef USBDM::GpioD<0,ActiveLow>                            Switch4a;                                     // PTD0(p41)

/// DebugLed
typedef USBDM::GpioD<5,ActiveHigh>                           DebugLed;                                     // PTD5(p46)

/// Touch Panel IRQ
typedef USBDM::GpioD<4,ActiveHigh>                           TouchIrq;                                     // PTD4(p45)

/// Touch Wakeup
typedef Llwu::Pin<LlwuPin_Ptd4>                              TouchWakeup;                                  // PTD4(p45)

typedef Pit::Channel<0>                                      ButtonTimerChannel;                           // PIT_CH0

/// SPI, Serial Peripheral Interface
typedef Spi0                                                 MySPI;                                        

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
