/**
 * @file     lptmr.h (180.ARM_Peripherals/Project_Headers/lptmr.h)
 * @brief    Low power timer interface
 */

#ifndef HEADER_LPTMR_H
#define HEADER_LPTMR_H

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include <climits>
#include <cmath>
#include "derivative.h"
#include "system.h"
#include "pin_mapping.h"

// No handler defined for LPTMR0 


namespace USBDM {

/**
 * @addtogroup LPTMR_Group LPTMR, Low Power Timer
 * @brief Abstraction for Low Power Timer
 * @{
 */
#if true // /LPTMR/_BasicInfoGuard
/**
 * Peripheral information for LPTMR, Low Power Timer.
 * 
 * This may include pin information, constants, register addresses, and default register values,
 * along with simple accessor functions.
 */

   /**
    * Timer Enable
    * (lptmr_csr_ten)
    *
    * Enables timer
    */
   enum LptmrCsrTen : uint8_t {
      LptmrCsrTen_Disabled   = LPTMR_CSR_TEN(0),  ///< Disabled
      LptmrCsrTen_Enabled    = LPTMR_CSR_TEN(1),  ///< Enabled
   };

   /**
    * Operation mode of the LPTMR
    * (lptmr_csr_tms)
    *
    * Selects between timer Interval and Pulse Counting
    * Should only be altered when timer is disabled.
    */
   enum LptmrMode : uint8_t {
      LptmrMode_TimeInterval    = LPTMR_CSR_TMS(0),  ///< Time Interval mode
      LptmrMode_PulseCounting   = LPTMR_CSR_TMS(1),  ///< Pulse Counter mode
   };

   /**
    * Timer action on event
    * (lptmr_csr_tie)
    *
    * Enables LPTMR interrupts
    */
   enum LptmrEventAction : uint8_t {
      LptmrEventAction_None        = LPTMR_CSR_TIE(0),  ///< None
      LptmrEventAction_Interrupt   = LPTMR_CSR_TIE(1),  ///< Interrupt
   };

   /**
    * Counter Action on Compare Event
    * (lptmr_csr_tfc)
    *
    * Counter action when compare event occurs
    * The counter can continue counting or be reset to zero.
    * Should only be altered when timer is disabled.
    */
   enum LptmrCounterActionOnEvent : uint8_t {
      LptmrCounterActionOnEvent_Reset   = LPTMR_CSR_TFC(0),  ///< Counter is reset on event
      LptmrCounterActionOnEvent_None    = LPTMR_CSR_TFC(1),  ///< No effect on counter
   };

   /**
    * Timer Compare Flag
    * (lptmr_csr_tcf)
    *
    * Flag is set when the LPTMR is enabled and the CNR equals the CMR and increments.
    * Flag is cleared when the LPTMR is disabled or a logic 1 is written to it.
    */
   enum LptmrCompareFlag : uint8_t {
      LptmrCompareFlag_NoEvent   = LPTMR_CSR_TCF(0),  ///< No event
      LptmrCompareFlag_Event     = LPTMR_CSR_TCF(1),  ///< Event
   };

   /**
    * Clock source for LPTMR
    * (lptmr_psr_pcs)
    *
    * Selects the clock source for LPTMR
    * Should only be altered when timer is disabled.
    */
   enum LptmrClockSel : uint8_t {
      LptmrClockSel_Mcgirclk   = LPTMR_PSR_PCS(0),  ///< MCG Internal Reference Clock (MCGIRCLK)
      LptmrClockSel_Lpoclk     = LPTMR_PSR_PCS(1),  ///< Low power oscillator (LPO - 1kHz)
      LptmrClockSel_Erclk32    = LPTMR_PSR_PCS(2),  ///< 32kHz Clock Source (ERCLK32)
      LptmrClockSel_Oscerclk   = LPTMR_PSR_PCS(3),  ///< Oscillator External Reference Clock (OSCERCLK)
   };

   /**
    * Prescaler Value
    * (lptmr_psr_prescaler)
    *
    * Configures the size of the Prescaler in Time Interval mode
    * Should only be altered when timer is disabled.
    */
   enum LptmrPrescale : uint8_t {
      LptmrPrescale_Direct        = LPTMR_PSR_PBYP(1)|LPTMR_PSR_PRESCALE(0),   ///< Prescaler = 1
      LptmrPrescale_DivBy_2       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(0),   ///< Prescaler = 2
      LptmrPrescale_DivBy_4       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(1),   ///< Prescaler = 4
      LptmrPrescale_DivBy_8       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(2),   ///< Prescaler = 8
      LptmrPrescale_DivBy_16      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(3),   ///< Prescaler = 16,
      LptmrPrescale_DivBy_32      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(4),   ///< Prescaler = 32,
      LptmrPrescale_DivBy_64      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(5),   ///< Prescaler = 64
      LptmrPrescale_DivBy_128     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(6),   ///< Prescaler = 128
      LptmrPrescale_DivBy_256     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(7),   ///< Prescaler = 256
      LptmrPrescale_DivBy_512     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(8),   ///< Prescaler = 512
      LptmrPrescale_DivBy_1024    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(9),   ///< Prescaler = 1024
      LptmrPrescale_DivBy_2048    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(10),  ///< Prescaler = 2048
      LptmrPrescale_DivBy_4096    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(11),  ///< Prescaler = 4096
      LptmrPrescale_DivBy_8192    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(12),  ///< Prescaler = 8192
      LptmrPrescale_DivBy_16384   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(13),  ///< Prescaler = 16384
      LptmrPrescale_DivBy_32768   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(14),  ///< Prescaler = 32768
      LptmrPrescale_DivBy_65536   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(15),  ///< Prescaler = 65536
   };

   /**
    * Filter Value
    * (lptmr_psr_glitchFilter)
    *
    * Configures the size of the glitch filter in Pulse Counting mode
    * Should only be altered when timer is disabled.
    */
   enum LptmrGlitchFilter : uint8_t {
      LptmrGlitchFilter_Direct         = LPTMR_PSR_PBYP(1)|LPTMR_PSR_PRESCALE(0),   ///< No glitch filter
      LptmrGlitchFilter_2_clocks       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(1),   ///< 2 clock cycle glitch filter
      LptmrGlitchFilter_4_clocks       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(2),   ///< 4 clock cycle glitch filter
      LptmrGlitchFilter_8_clocks       = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(3),   ///< 8 clock cycle glitch filter
      LptmrGlitchFilter_16_clocks      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(4),   ///< 16 clock cycle glitch filter
      LptmrGlitchFilter_32_clocks      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(5),   ///< 32 clock cycle glitch filter
      LptmrGlitchFilter_64_clocks      = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(6),   ///< 64 clock cycle glitch filter
      LptmrGlitchFilter_128_clocks     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(7),   ///< 128 clock cycle glitch filter
      LptmrGlitchFilter_256_clocks     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(8),   ///< 256 clock cycle glitch filter
      LptmrGlitchFilter_512_clocks     = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(9),   ///< 512 clock cycle glitch filter
      LptmrGlitchFilter_1024_clocks    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(10),  ///< 1024 clock cycle glitch filter
      LptmrGlitchFilter_2048_clocks    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(11),  ///< 2048 clock cycle glitch filter
      LptmrGlitchFilter_4096_clocks    = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(12),  ///< 4096 clock cycle glitch filter
      LptmrGlitchFilter_81924_clocks   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(13),  ///< 8192 clock cycle glitch filter
      LptmrGlitchFilter_16384_clocks   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(14),  ///< 16384 clock cycle glitch filter
      LptmrGlitchFilter_32768_clocks   = LPTMR_PSR_PBYP(0)|LPTMR_PSR_PRESCALE(15),  ///< 32768 clock cycle glitch filter
   };

   /**
    * Input Pin
    * (lptmr_csr_tps)
    *
    * Input source to be used in Pulse Counter mode
    * Should only be altered when timer is disabled.
    */
   enum LptmrInput : uint8_t {
      LptmrInput_CMP0   = LPTMR_CSR_TPS(0),  ///< CMP0
      LptmrInput_ALT1   = LPTMR_CSR_TPS(1),  ///< LPTMR0_ALT1 [-]
      LptmrInput_ALT2   = LPTMR_CSR_TPS(2),  ///< LPTMR0_ALT2 [-]
   };

   /**
    * Pin Polarity
    * (lptmr_csr_tpp)
    *
    * Polarity of the input source in Pulse Counter mode
    * Should only be altered when timer is disabled.
    */
   enum LptmrInputEdge : uint8_t {
      LptmrInputEdge_Rising    = LPTMR_CSR_TPP(0),  ///< Active-high, increment count on rising-edge
      LptmrInputEdge_Falling   = LPTMR_CSR_TPP(1),  ///< Active-low, increment count on falling-edge
   };


   // Bit operators for PSR register fields
   constexpr inline uint8_t operator|(LptmrClockSel op1, LptmrPrescale op2)         { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrClockSel op1, LptmrGlitchFilter op2)     { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrPrescale op1, LptmrClockSel op2)         { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrPrescale op1, LptmrGlitchFilter op2)     { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrGlitchFilter op1, LptmrClockSel op2)     { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrGlitchFilter op1, LptmrPrescale op2)     { return uint8_t(op1)|uint8_t(op2); };
   

   // Bit operators for CSR register fields
   constexpr inline uint8_t operator|(LptmrInput op1, LptmrInputEdge op2)     { return uint8_t(op1)|uint8_t(op2); };
   constexpr inline uint8_t operator|(LptmrInputEdge op1, LptmrInput op2)     { return uint8_t(op1)|uint8_t(op2); };
   
class LptmrBasicInfo {

public:

   //! Common class based callback code has been generated for this class of peripheral
   // (_BasicInfoIrqGuard)
   static constexpr bool irqHandlerInstalled = true;
   
   /**
    * Type definition for Lptmr interrupt call back.
    */
   typedef void (*CallbackFunction)();
   
   // Pointer to LPTMR hardware instance
   volatile LPTMR_Type * const lptmr;
   
   /**
    * Constructor
    *
    * @param lptmr LPTMR hardware instance
    */
   constexpr LptmrBasicInfo(volatile LPTMR_Type * lptmr) : lptmr(lptmr) {
   }
   
   /**
    * Get Clock source for LPTMR frequency
    * (lptmr_psr_pcs)
    *
    * @param lptmrClockSel Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
   
    * @return Clock frequency in Hz
    */
   static uint32_t getInputClockFrequency(LptmrClockSel lptmrClockSel) {
   
      switch(lptmrClockSel) {
         default:
         case LptmrClockSel_Mcgirclk : return McgInfo::getMcgIrClock();  ///< MCG Internal Reference Clock (MCGIRCLK)
         case LptmrClockSel_Lpoclk   : return SimInfo::getLpoClock();    ///< Low power oscillator (LPO - 1kHz)
         case LptmrClockSel_Erclk32  : return SimInfo::getErc32kClock(); ///< 32kHz Clock Source (ERCLK32)
         case LptmrClockSel_Oscerclk : return Osc0Info::getOscerClock(); ///< Oscillator External Reference Clock (OSCERCLK)

      }
   }
   
   /**
    * Calculate timing information based on desired duration and selected clock (from psr.pcs)
    *
    * @param[in]     duration   Desired period or event duration
    * @param[inout]  psr        Input: psr.pcs Output: updated with psr.prescale and psr.pbyp
    * @param[out]    cmr        Compare register value
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for psr.prescale and psr.pbyp
    */
   static ErrorCode calculateDurationValues(Seconds duration, uint8_t &psr, uint32_t &cmr) {
   
      float inputClock = getInputClockFrequency(LptmrClockSel(psr&LPTMR_PSR_PCS_MASK));
   
      int      prescaleFactor=1;
      uint32_t prescalerValue=0;
      while (prescalerValue<=16) {
         float    clockFrequency = inputClock/prescaleFactor;
         uint32_t mod   = rintf(float(duration*clockFrequency))-1;
         if (mod <= LPTMR_CMR_COMPARE_MASK) {
            cmr  = mod;
            psr  = (psr&LPTMR_PSR_PCS_MASK)|LPTMR_PSR_PRESCALE(prescalerValue-1)|LPTMR_PSR_PBYP(prescalerValue==0);
            return E_NO_ERROR;
         }
         prescalerValue++;
         prescaleFactor <<= 1;
      }
      // Too long a period
      return setAndCheckErrorCode(E_TOO_LARGE);
   }
   
   /**
    * Truncate Tick value to correct range for modulo calculations.
    *
    * @param ticks Value to truncate in Ticks
    *
    * @return Truncated value in Ticks
    */
   static Ticks modulo(const Ticks &ticks) {
   
      return Ticks(unsigned(ticks) & LPTMR_CNR_COUNTER_MASK);
   }

   /**
    * Get Timer Compare Flag
    * (lptmr_csr_tcf)
    *
    * @return Flag is set when the LPTMR is enabled and the CNR equals the CMR and increments.
    *        Flag is cleared when the LPTMR is disabled or a logic 1 is written to it.
    */
   LptmrCompareFlag getEventFlag() const {
      return LptmrCompareFlag(lptmr->CSR&LPTMR_CSR_TCF_MASK);
   }
   
   /**
    * Clear Timer Compare Flag
    * (lptmr_csr_tcf)
    *
    * Flag is set when the LPTMR is enabled and the CNR equals the CMR and increments.
    * Flag is cleared when the LPTMR is disabled or a logic 1 is written to it.
    */
   void clearEventFlag() const {
      // w1c and mixed register
      lptmr->CSR = lptmr->CSR|LPTMR_CSR_TCF_MASK;
   }
   
   /**
    * Set Timer action on event
    * (lptmr_csr_tie)
    *
    * @param lptmrEventAction Enables LPTMR interrupts
    */
   void setEventAction(LptmrEventAction lptmrEventAction) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TIE_MASK) | uint32_t(lptmrEventAction);
   }
   
   /**
    * Get Timer action on event
    * (lptmr_csr_tie)
    *
    * @return Enables LPTMR interrupts
    */
   LptmrEventAction getEventAction() const {
      return LptmrEventAction(lptmr->CSR&LPTMR_CSR_TIE_MASK);
   }
   
   /**
    * Set Input Pin
    * (lptmr_csr_tps)
    *
    * @param lptmrInput Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   void setInputSelect(LptmrInput lptmrInput) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TPS_MASK) | uint32_t(lptmrInput);
   }
   
   /**
    * Get Input Pin
    * (lptmr_csr_tps)
    *
    * @return Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   LptmrInput getInputSelect() const {
      return LptmrInput(lptmr->CSR&LPTMR_CSR_TPS_MASK);
   }
   
   /**
    * Set Pin Polarity
    * (lptmr_csr_tpp)
    *
    * @param lptmrInputEdge Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   void setInputEdge(LptmrInputEdge lptmrInputEdge) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TPP_MASK) | uint32_t(lptmrInputEdge);
   }
   
   /**
    * Get Pin Polarity
    * (lptmr_csr_tpp)
    *
    * @return Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   LptmrInputEdge getInputEdge() const {
      return LptmrInputEdge(lptmr->CSR&LPTMR_CSR_TPP_MASK);
   }
   
   /**
    * Set Counter Action on Compare Event
    * (lptmr_csr_tfc)
    *
    * @param lptmrCounterActionOnEvent Counter action when compare event occurs
    *        The counter can continue counting or be reset to zero.
    *        Should only be altered when timer is disabled.
    */
   void setCounterActionOnEvent(LptmrCounterActionOnEvent lptmrCounterActionOnEvent) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TFC_MASK) | uint32_t(lptmrCounterActionOnEvent);
   }
   
   /**
    * Get Counter Action on Compare Event
    * (lptmr_csr_tfc)
    *
    * @return Counter action when compare event occurs
    *        The counter can continue counting or be reset to zero.
    *        Should only be altered when timer is disabled.
    */
   LptmrCounterActionOnEvent getCounterActionOnEvent() const {
      return LptmrCounterActionOnEvent(lptmr->CSR&LPTMR_CSR_TFC_MASK);
   }
   
   /**
    * Set Operation mode of the LPTMR
    * (lptmr_csr_tms)
    *
    * @param lptmrMode Selects between timer Interval and Pulse Counting
    *        Should only be altered when timer is disabled.
    */
   void setMode(LptmrMode lptmrMode) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TMS_MASK) | uint32_t(lptmrMode);
   }
   
   /**
    * Get Operation mode of the LPTMR
    * (lptmr_csr_tms)
    *
    * @return Selects between timer Interval and Pulse Counting
    *        Should only be altered when timer is disabled.
    */
   LptmrMode getMode() const {
      return LptmrMode(lptmr->CSR&LPTMR_CSR_TMS_MASK);
   }
   
   /**
    * Set Timer Enable
    * (lptmr_csr_ten)
    *
    * @param lptmrCsrTen Enables timer
    */
   void setEnable(LptmrCsrTen lptmrCsrTen) const {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TEN_MASK) | uint32_t(lptmrCsrTen);
   }
   
   /**
    * Get Timer Enable
    * (lptmr_csr_ten)
    *
    * @return Enables timer
    */
   LptmrCsrTen getEnable() const {
      return LptmrCsrTen(lptmr->CSR&LPTMR_CSR_TEN_MASK);
   }
   
   /**
    * Set Input Pin and Pin Polarity
    * (lptmr_csr_tps,lptmr_csr_tpp)
    *
    * @param lptmrInput     Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    * @param lptmrInputEdge Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   void setInput(
         LptmrInput     lptmrInput,
         LptmrInputEdge lptmrInputEdge = LptmrInputEdge_Rising) const {
      lptmr->CSR = (lptmr->CSR&~(LPTMR_CSR_TPS_MASK|LPTMR_CSR_TPP_MASK)) | uint32_t(lptmrInput|lptmrInputEdge);
   }
   
   /**
    * Set Clock source for LPTMR
    * (lptmr_psr_pcs)
    *
    * @param lptmrClockSel Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    */
   void setClockSource(LptmrClockSel lptmrClockSel) const {
      lptmr->PSR = (lptmr->PSR&~LPTMR_PSR_PCS_MASK) | uint32_t(lptmrClockSel);
   }
   
   /**
    * Get Clock source for LPTMR
    * (lptmr_psr_pcs)
    *
    * @return Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    */
   LptmrClockSel getClockSource() const {
      return LptmrClockSel(lptmr->PSR&LPTMR_PSR_PCS_MASK);
   }
   
   /**
    * Set Timer Compare Value
    * (lptmr_cmr_compare)
    *
    * @param ticks Comparison value
    *        The timer comparison flag is set when the counter reaches this value and increments. 
    *        The hardware trigger will assert until the next time the counter increments. 
    *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
    *        The CMR must only be altered when timer is disabled or when TCF is set.
    */
   void setCompareThreshold(const Ticks& ticks) const {
      lptmr->CMR = (lptmr->CMR&~LPTMR_CMR_COMPARE_MASK) | uint32_t(LPTMR_CMR_COMPARE(ticks));
   }
   
   /**
    * Get Timer Compare Value
    * (lptmr_cmr_compare)
    *
    * @return Comparison value
    *        The timer comparison flag is set when the counter reaches this value and increments. 
    *        The hardware trigger will assert until the next time the counter increments. 
    *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
    *        The CMR must only be altered when timer is disabled or when TCF is set.
    */
   Ticks getCompareThreshold() const {
      return Ticks((lptmr->CMR&LPTMR_CMR_COMPARE_MASK)>>LPTMR_CMR_COMPARE_SHIFT);
   }
   
   /**
    * Set Clock source for LPTMR and Prescaler Value
    * (lptmr_psr_pcs,lptmr_psr_prescaler)
    *
    * These settings are used for the clock prescaler in timer mode.
    *
    * @param lptmrClockSel Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    * @param lptmrPrescale Configures the size of the Prescaler in Time Interval mode
    *        Should only be altered when timer is disabled.
    */
   void setClock(
         LptmrClockSel lptmrClockSel,
         LptmrPrescale lptmrPrescale) const {
   
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
      lptmr->PSR   = lptmrClockSel|lptmrPrescale;
      lptmr->CSR   = csr;
   }

   /**
    * Set Clock source for LPTMR and Filter Value
    * (lptmr_psr_pcs,lptmr_psr_glitchFilter)
    *
    * These settings are used for the glitch filter in pulse-counting mode.
    *
    * @param lptmrClockSel     Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    * @param lptmrGlitchFilter Configures the size of the glitch filter in Pulse Counting mode
    *        Should only be altered when timer is disabled.
    */
   void setClock(
         LptmrClockSel     lptmrClockSel,
         LptmrGlitchFilter lptmrGlitchFilter) const {
   
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
      lptmr->PSR   = lptmrClockSel|lptmrGlitchFilter;
      lptmr->CSR   = csr;
   }

   /**
    * Get Clock source for LPTMR frequency
    * (lptmr_psr_pcs)
    *
    * @return Clock frequency in Hz
    */
   uint32_t getInputClockFrequency() const {
   
      return LptmrBasicInfo::getInputClockFrequency(LptmrClockSel(LPTMR_PSR_PCS_MASK&lptmr->PSR));
   }
   
   /**
    * Get clock frequency after prescaler
    * (lptmr_psr_pcs)
    *
    * @return Frequency as a float in Hz
    */
   float getClockFrequencyF() const {
   
      float freq = getInputClockFrequency();
      if (lptmr->PSR&LPTMR_PSR_PBYP_MASK) {
         return freq;
      }
      return freq/(1<<(((lptmr->PSR&LPTMR_PSR_PRESCALE_MASK)>>LPTMR_PSR_PRESCALE_SHIFT)+1));
   }
   
   /**
    * Get clock frequency
    * (lptmr_psr_pcs)
    *
    * @return Frequency as a uint32_t in Hz (may underflow)
    */
   uint32_t getClockFrequency() const {
   
      uint32_t freq = getInputClockFrequency();
      if (lptmr->PSR&LPTMR_PSR_PBYP_MASK) {
         return freq;
      }
      return freq/(1<<(((lptmr->PSR&LPTMR_PSR_PRESCALE_MASK)>>LPTMR_PSR_PRESCALE_SHIFT)+1));
   }
   
   /**
    * Converts a number in ticks to time in microseconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in microseconds
    *
    * @note Assumes prescale has been chosen appropriately.
    * @note Rudimentary range checking only. Sets error code.
    */
   uint32_t convertTicksToMicroseconds(Ticks ticks) const {
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (((uint64_t)ticks)*1000000)/(unsigned)tickRate;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Converts a number in ticks to time in milliseconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in milliseconds
    *
    * @note Assumes prescale has been chosen appropriately.
    * @note Rudimentary range checking only. Sets error code.
    */
   unsigned convertTicksToMilliseconds(Ticks ticks) const {
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (((uint64_t)ticks)*1000)/(unsigned)tickRate;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return unsigned(rv);
   }
   
   /**
    * Converts a number in ticks to time in seconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in seconds (as float)
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   Seconds convertTicksToSeconds(Ticks ticks) const {
      float tickRate = getClockFrequencyF();
      return Seconds(((float)ticks)/tickRate);
   }
   
   /**
    * Converts a time in microseconds to number of ticks.
    *
    * @param[in]  time Time in microseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   Ticks convertMicrosecondsToTicks(int time) const {
   
      // Calculate period
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (unsigned)((uint64_t)time*tickRate)/1000000;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   /**
    * Converts a time in milliseconds to number of ticks.
    *
    * @param[in]  time Time in milliseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   Ticks convertMillisecondsToTicks(int time) const {
   
      // Calculate period
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (unsigned)((uint64_t)time*tickRate)/1000;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   
   /**
    * Converts a time in seconds to number of ticks
    *
    * @param[in]  time Time in seconds (float!)
    *
    * @return Time in ticks
    *
    * @note Uses floating point
    * @note Rudimentary range checking only. Sets error code.
    */
   Ticks convertSecondsToTicks(Seconds time) const {
   
      // Calculate period
      float    tickRate = getClockFrequencyF();
      uint64_t rv       = (unsigned)((float)time*tickRate);
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   
   /**
    * Calculate filter information based on desired interval
    * This calculates a clock prescaler so that the filter interval is at least the given value.
    *
    * @param[in]     interval   Desired filter interval
    * @param[inout]  psr        Input: psr.pcs Output: updated with psr.prescale and psr.pbyp
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for psr.prescale and psr.pbyp
    */
   ErrorCode calculateFilterValues(Seconds interval, uint8_t &psr) const {
   
      float    inputClock = LptmrBasicInfo::getInputClockFrequency(LptmrClockSel(psr&LPTMR_PSR_PCS_MASK));
      int      prescaleFactor=1;
      uint32_t prescalerValue=0;
      while (prescalerValue<=16) {
         if ((float)(interval*prescaleFactor) < inputClock) {
            psr  = (psr&LPTMR_PSR_PCS_MASK)|LPTMR_PSR_PRESCALE(prescalerValue-1)|LPTMR_PSR_PBYP(prescalerValue==0);
            return E_NO_ERROR;
         }
         prescalerValue++;
         prescaleFactor <<= 1;
      }
      // Too long a duration
      return setAndCheckErrorCode(E_TOO_LARGE);
   }
   
   /**
    * Set period of timer.
    *
    * @param[in]  period Period in seconds as a float
    *
    * @note Will enable and adjust the pre-scaler to appropriate value.

    *       The clock source should be selected by setClock() before using this function.
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for psr.prescale and psr.pbyp
    */
   ErrorCode setPeriod(Seconds period) const {
   
      uint8_t  psr = lptmr->PSR;
      uint32_t cmr;
      ErrorCode rc = LptmrBasicInfo::calculateDurationValues(period, psr, cmr);
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable before changing clock
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
   
      lptmr->CMR  = cmr;
      lptmr->PSR  = psr;
   
      lptmr->CSR  = csr;
   
      return E_NO_ERROR;
   }
   
   /**
    * Set glitch filter interval.
    * This adjusts the clock prescaler so that the filter interval is at least the given value.
    *
    * @param[in]  interval Interval in seconds as a float
    *
    * @note Will enable and adjust the pre-scaler to appropriate value.

    *       The clock source should be selected by setClock() before using this function.
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for PBYP & PRESCALE
    */
   ErrorCode setFilterInterval(Seconds interval) const {
   
      uint8_t  psr = lptmr->PSR;
   
      ErrorCode rc = calculateFilterValues(interval, psr);
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
   
      lptmr->PSR  = psr;
   
      lptmr->CSR  = csr;
   
      return E_NO_ERROR;
   }
   
   /**
    * Get timer counter value
    *
    * @return Timer value in ticks.
    */
   Ticks getCounterValue() const {
      // It is necessary to write to the CNR to capture current value
      lptmr->CNR = 0;
      return (Ticks)(lptmr->CNR);
   }
   
   /**
    * Restarts the counter
    * This restarts the timer by disabling and re-enabling with the same configuration
    */
   void restart() const {
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      lptmr->CSR   = csr;
   }
   
   /**
    * Class used to do initialisation of LPTMR
    */
   class Init {
   
   private:
      /**
       * Prevent implicit parameter conversions
       */
      template <typename... Types>
      constexpr Init(Types...) = delete;
   
      /**
       * No Copy Constructor
       */
      constexpr Init(const Init &other) = delete;
   
   protected:
      /**
       * Default Constructor
       */
      constexpr Init() = default;
   
   public:
      // Timer Compare Interval (lptmr_cmrPeriod)
      Seconds cmrperiod = 0_s;

      // Timer Compare Value (lptmr_cmr_compare)
      uint16_t cmr = 0;

      // Prescaler Value (lptmr_psr_prescaler)
      // Clock source for LPTMR (lptmr_psr_pcs)
      uint8_t psr = 0;

      // Timer action on event (lptmr_csr_tie)
      // Counter Action on Compare Event (lptmr_csr_tfc)
      uint8_t csr = 0;

   }; // class LptmrBasicInfo::Init
   
   /**
    * Class used to do initialisation of LPTMR in Time Interval Mode
    *
    * This class has a templated constructor that accepts various values:
    *
    * @note This constructor may be used to create a const instance in ROM
    *
    * Example:
    * @code
    * %(static)const Lptmr0::TimeIntervalModeInit lptmrInit {
    *    LptmrResetOn_Compare,    // Timer Free-Running Counter enable
    *    LptmrInterrupt_Disabled, // Timer interrupt enable
    *    LptmrClockSel_Oscerclk,  // Clock Source
    *    LptmrPrescale_Direct,    // Prescaler Value
    *    100_ms,                  // Timer Compare Register
    * };
    *
    * // Initialise LPTMR0 in Time Interval mode using values specified above
    * Lptmr0.configure(lptmrInit)
    * @endcode
    */
   class TimeIntervalModeInit : public Init {
   
   private:
      /**
       * No Copy Constructor
       */
      constexpr TimeIntervalModeInit(const Init &other) = delete;
   
   public:
   
      /**
       * Default Constructor
       */
      constexpr TimeIntervalModeInit() : Init() {
   
         csr = (csr & ~LPTMR_CSR_TMS_MASK) | LptmrMode_TimeInterval;
      }
   
      /**
       * Constructor for Timer action on event
       * (lptmr_csr_tie)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrEventAction Enables LPTMR interrupts
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(LptmrEventAction lptmrEventAction, Types... rest) : TimeIntervalModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TIE_MASK) | uint32_t(lptmrEventAction);
      }
   
      /**
       * Constructor for Counter Action on Compare Event
       * (lptmr_csr_tfc)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrCounterActionOnEvent Counter action when compare event occurs
       *        The counter can continue counting or be reset to zero.
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(LptmrCounterActionOnEvent lptmrCounterActionOnEvent, Types... rest) : TimeIntervalModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TFC_MASK) | uint32_t(lptmrCounterActionOnEvent);
      }
   
      /**
       * Constructor for Prescaler Value
       * (lptmr_psr_prescaler)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrPrescale Configures the size of the Prescaler in Time Interval mode
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(LptmrPrescale lptmrPrescale, Types... rest) : TimeIntervalModeInit(rest...) {
   
         psr = (psr&~(LPTMR_PSR_PBYP_MASK|LPTMR_PSR_PRESCALE_MASK)) | uint32_t(lptmrPrescale);
      }
   
      /**
       * Constructor for Clock source for LPTMR
       * (lptmr_psr_pcs)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrClockSel Selects the clock source for LPTMR
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(LptmrClockSel lptmrClockSel, Types... rest) : TimeIntervalModeInit(rest...) {
   
         psr = (psr&~LPTMR_PSR_PCS_MASK) | uint32_t(lptmrClockSel);
      }
   
      /**
       * Constructor for Timer Compare Value
       * (lptmr_cmr_compare)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param ticks Comparison value
       *        The timer comparison flag is set when the counter reaches this value and increments. 
       *        The hardware trigger will assert until the next time the counter increments. 
       *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
       *        The CMR must only be altered when timer is disabled or when TCF is set.
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(const Ticks& ticks, Types... rest) : TimeIntervalModeInit(rest...) {
   
         cmr = (cmr&~LPTMR_CMR_COMPARE_MASK) | uint32_t(LPTMR_CMR_COMPARE(ticks));
      }
   
      /**
       * Constructor for Timer Compare Interval
       * (lptmr_cmrPeriod)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param seconds Comparison value
       *        The timer comparison flag is set when the counter reaches this value and increments. 
       *        The hardware trigger will assert until the next time the counter increments. 
       *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
       */
      template <typename... Types>
      constexpr TimeIntervalModeInit(const Seconds& seconds, Types... rest) : TimeIntervalModeInit(rest...) {
   
         cmrperiod = seconds;
      }
   
   }; // class LptmrBasicInfo::TimeIntervalModeInit
   
   /**
    * Class used to do initialisation of LPTMR in Pulse Counting Mode
    *
    * This class has a templated constructor that accepts various values:
    *
    * @note This constructor may be used to create a const instance in ROM
    *
    * @code
    * Example:
    * static const Lptmr0::PulseCountingModeInit lptmrInit {
    *    LptmrPinSel_Cmp0,           // Timer Pin Select for Pulse Counter mode
    *    LptmrInputEdge_Rising,      // Timer Pin Polarity for Pulse Counter mode
    *    LptmrClockSel_Oscerclk,     // Clock Source
    *    LptmrGlitchFilter_Direct,   // Filter Value
    *    LptmrInterrupt_Disabled,    // Timer interrupt enable
    *    LptmrResetOn_Compare,       // Timer Free-Running Counter enable
    *    916_ticks,                  // Timer Compare Register
    * };
    *
    * // Initialise LPTMR0 in Pulse Counting mode using values specified above
    * Lptmr0.configure(lptmrInit)
    * @endcode
    */
   class PulseCountingModeInit : public Init {
   
   private:
      /**
       * No Copy Constructor
       */
      constexpr PulseCountingModeInit(const Init &other) = delete;
   
   public:
   
      /**
       * Default Constructor
       */
      constexpr PulseCountingModeInit() : Init() {
   
         csr = (csr & ~LPTMR_CSR_TMS_MASK) | LptmrMode_PulseCounting;
      }
   
      /**
       * Constructor for Timer action on event
       * (lptmr_csr_tie)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrEventAction Enables LPTMR interrupts
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrEventAction lptmrEventAction, Types... rest) : PulseCountingModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TIE_MASK) | uint32_t(lptmrEventAction);
      }
   
      /**
       * Constructor for Counter Action on Compare Event
       * (lptmr_csr_tfc)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrCounterActionOnEvent Counter action when compare event occurs
       *        The counter can continue counting or be reset to zero.
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrCounterActionOnEvent lptmrCounterActionOnEvent, Types... rest) : PulseCountingModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TFC_MASK) | uint32_t(lptmrCounterActionOnEvent);
      }
   
      /**
       * Constructor for Clock source for LPTMR
       * (lptmr_psr_pcs)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrClockSel Selects the clock source for LPTMR
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrClockSel lptmrClockSel, Types... rest) : PulseCountingModeInit(rest...) {
   
         psr = (psr&~LPTMR_PSR_PCS_MASK) | uint32_t(lptmrClockSel);
      }
   
      /**
       * Constructor for Timer Compare Value
       * (lptmr_cmr_compare)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param ticks Comparison value
       *        The timer comparison flag is set when the counter reaches this value and increments. 
       *        The hardware trigger will assert until the next time the counter increments. 
       *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
       *        The CMR must only be altered when timer is disabled or when TCF is set.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(const Ticks& ticks, Types... rest) : PulseCountingModeInit(rest...) {
   
         cmr = (cmr&~LPTMR_CMR_COMPARE_MASK) | uint32_t(LPTMR_CMR_COMPARE(ticks));
      }
   
      /**
       * Constructor for Input Pin
       * (lptmr_csr_tps)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrInput Input source to be used in Pulse Counter mode
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrInput lptmrInput, Types... rest) : PulseCountingModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TPS_MASK) | uint32_t(lptmrInput);
      }
   
      /**
       * Constructor for Pin Polarity
       * (lptmr_csr_tpp)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrInputEdge Polarity of the input source in Pulse Counter mode
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrInputEdge lptmrInputEdge, Types... rest) : PulseCountingModeInit(rest...) {
   
         csr = (csr&~LPTMR_CSR_TPP_MASK) | uint32_t(lptmrInputEdge);
      }
   
      /**
       * Constructor for Filter Value
       * (lptmr_psr_glitchFilter)
       *
       * @tparam   Types
       * @param    rest
       *
       * @param lptmrGlitchFilter Configures the size of the glitch filter in Pulse Counting mode
       *        Should only be altered when timer is disabled.
       */
      template <typename... Types>
      constexpr PulseCountingModeInit(LptmrGlitchFilter lptmrGlitchFilter, Types... rest) : PulseCountingModeInit(rest...) {
   
         psr = (psr&~(LPTMR_PSR_PBYP_MASK|LPTMR_PSR_PRESCALE_MASK)) | uint32_t(lptmrGlitchFilter);
      }
   
   }; // class LptmrBasicInfo::PulseCountingModeInit
   
   /**
    * Configure LPTMR from values specified in init.
    * This routine does not configure pins or interrupt handlers
    *
    * @param lptmr           Hardware instance pointer
    * @param init            Class containing initialisation values
    *
    * @return Error code
    */
   static ErrorCode configure(
                  volatile LPTMR_Type *lptmr,
                  const Init    &init) {
   
      // Clock source for LPTMR (lptmr_psr_pcs)
      uint8_t psr = init.psr;
   
      // Timer Compare Value (lptmr_cmr_compare)
      uint32_t  cmr = init.cmr;
   
      // Timer Compare Interval (lptmr_cmrPeriod)
      if (init.cmrperiod != 0) {                
         // Calculate values from duration in seconds                
         ErrorCode rc = calculateDurationValues(init.cmrperiod, psr, cmr);                
         if (rc != E_NO_ERROR) {                
            return rc;                
         }                
      };
   
      // Timer Compare Flag (lptmr_csr_tcf)
      // Timer action on event (lptmr_csr_tie)
      // Input Pin (lptmr_csr_tps)
      // Pin Polarity (lptmr_csr_tpp)
      // Counter Action on Compare Event (lptmr_csr_tfc)
      // Operation mode of the LPTMR (lptmr_csr_tms)
      // Configure while disabled                
      lptmr->CSR = init.csr;
   
      // Clock source for LPTMR (lptmr_psr_pcs)
      lptmr->PSR = psr;
   
      // Timer Compare Value (lptmr_cmr_compare)
      lptmr->CMR = cmr;
   
      // Timer Enable (lptmr_csr_ten)
      // Timer Compare Flag (lptmr_csr_tcf)
      // Timer action on event (lptmr_csr_tie)
      // Input Pin (lptmr_csr_tps)
      // Pin Polarity (lptmr_csr_tpp)
      // Counter Action on Compare Event (lptmr_csr_tfc)
      // Operation mode of the LPTMR (lptmr_csr_tms)
      lptmr->CSR = init.csr|LPTMR_CSR_TEN_MASK;
   
      return E_NO_ERROR;
   }
   
   /**
    * Configure LPTMR from values specified in init
    * This routine does not configure pins or interrupt handlers
    *
    * @param init Class containing initialisation values
    */
   ErrorCode configure(const Init &init) const {
   
      return configure(lptmr, init);
   }
   
}; // class LptmrBasicInfo 

class Lptmr0Info : public LptmrBasicInfo {

public:

   //! Number of signals available in info table
   static constexpr int numSignals  = 3;

   //! Information for each signal of peripheral
   static constexpr PinInfo  info[] = {

         //      Signal                 Pin                                  PinIndex                PCR value
         /*   0: --                   = --                             */  { PinIndex::INVALID_PCR,  PcrValue(0)         },
         /*   1: LPTMR0_ALT1          = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
         /*   2: LPTMR0_ALT2          = --                             */  { PinIndex::UNMAPPED_PCR, PcrValue(0)         },
   };

   /**
    * Initialise pins used by peripheral
    *
    * @note Only the lower 16-bits of the PCR registers are affected
    */
   static void initPCRs() {
   }

   /**
    * Release pins used by peripheral
    *
    * @note Only the lower 16-bits of the PCR registers are affected
    */
   static void clearPCRs() {
   }

   /*
    * Template:lptmr0
    */
   //! Map all allocated pins on a peripheral when enabled
   static constexpr bool mapPinsOnEnable = true;


   
   /**
    * Configures all mapped pins associated with LPTMR0
    *
    * @note Locked pins will be unaffected
    */
   static void configureAllPins() {
   
      // Configure pins if selected and not already locked
      if constexpr (mapPinsOnEnable) {
         initPCRs();
      }
   }
   
   /**
    * Disabled all mapped pins associated with LPTMR0
    *
    * @note Only the lower 16-bits of the PCR registers are modified
    *
    * @note Locked pins will be unaffected
    */
   static void disableAllPins() {
   
      // Disable pins if selected and not already locked
      if constexpr (mapPinsOnEnable) {
         clearPCRs();
      }
   }
   
   //! Class based interrupt code has been generated for this class of peripheral
   // (_BasicInfoIrqGuard)
   static constexpr bool irqHandlerInstalled = true;
   
   //! IRQ numbers for hardware
   static constexpr IRQn_Type irqNums[]  = LPTMR0_IRQS;
   
   //! Number of IRQs for hardware
   static constexpr uint32_t irqCount  = sizeofArray(irqNums);
   
   /**
    * Enable interrupts in NVIC
    */
   static void enableNvicInterrupts() {
      NVIC_EnableIRQ(irqNums[0]);
   }
   
   /**
    * Enable and set priority of interrupts in NVIC
    * Any pending NVIC interrupts are first cleared.
    *
    * @param[in]  nvicPriority  Interrupt priority
    */
   static void enableNvicInterrupts(NvicPriority nvicPriority) {
      enableNvicInterrupt(irqNums[0], nvicPriority);
   }
   
   /**
    * Disable interrupts in NVIC
    */
   static void disableNvicInterrupts() {
      NVIC_DisableIRQ(irqNums[0]);
   }
   
   template<typename T>
   using CallbackWrapper = USBDM::CallbackWrapper<T, Lptmr0Info>;
   
   /**
    * Function to wrap a member function as a static callback function
    * Example:
    * @code
    * class AClass {
    * public:
    *    int y;
    *
    *    // Member function used as callback
    *    // This function must match CallbackFunction
    *    void callbackFuction() {
    *       ...;
    *    }
    * };
    * ...
    *    AClass *tester = new AClass{};
    *
    *    auto cb = Lptmr0::wrapCallback(tester, &AClass::callbackFuction);
    *    Lptmr0::setCallback(cb);
    *   @endcode
    *
    * @tparam T               Type of class containing callback (inferred)
    *
    * @param classInstance    Pointer to instance of class
    * @param memberFunction   Pointer to the member function
    *
    * @return  Wrapper
    */
   template<typename T>
   static auto wrapCallback(T *classInstance, void (T::*memberFunction)()) {
      static CallbackWrapper<T> sClass(classInstance, memberFunction);
      return sClass.callback;
   }
   
   /**
    * LPTMR interrupt handler -  Calls LPTMR callback
    */
   static void irqHandler() {
   
      // Execute call-back
      sCallback();
   }
   
   /** Callback function for Lptmr0 */
   static inline CallbackFunction sCallback = unhandledCallback; // LPTMR0_IRQn;
   
   /**
    * Set interrupt callback function.
    *
    * @param  lptmrCallback Callback function to execute on interrupt
    *                             Use nullptr to remove callback.
    */
   static void setCallback(CallbackFunction lptmrCallback) {
      if (lptmrCallback == nullptr) {
         lptmrCallback = unhandledCallback;
      }
      // Allow either no handler set yet, setting same handler or removing handler
      usbdm_assert(
            (sCallback == unhandledCallback) ||
            (sCallback == lptmrCallback) ||
            (lptmrCallback == unhandledCallback),
            "Handler already set");
      sCallback = lptmrCallback;
   }
   
   /**
    *  Enable clock to Lptmr0
    */
   static void enableClock() {
      SIM->SCGC5 = SIM->SCGC5 | SIM_SCGC5_LPTMR0_MASK;
   }
   
   /**
    *  Disable clock to Lptmr0
    */
   static void disableClock() {
      SIM->SCGC5 = SIM->SCGC5 & ~SIM_SCGC5_LPTMR0_MASK;
   }
   
   /**
    * Basic enable of Lptmr0
    * Includes enabling clock and configuring all mapped pins if mapPinsOnEnable is selected in configuration
    */
   static void enable() {
      enableClock();
      configureAllPins();
   }
   
   /**
    * Disables Lptmr0
    */
   static void disable() {
   
      
      disableNvicInterrupts();
      disableAllPins();
      disableClock();
   }
   
   //! Hardware base address as uint32_t
   static constexpr uint32_t baseAddress = LPTMR0_BasePtr;
   
   //! Hardware base pointer
   static constexpr HardwarePtr<LPTMR_Type> lptmr = baseAddress;
   
   //! Peripheral instance number
   static constexpr unsigned instance = 0;
   
   /**
    * Information describing the priority and callback function for each interrupt
    */
   typedef InitVectors<Init, CallbackFunction, int, 1> Init;
   
   /**
    * Get Timer Compare Flag
    * (lptmr_csr_tcf)
    *
    * @return Flag is set when the LPTMR is enabled and the CNR equals the CMR and increments.
    *        Flag is cleared when the LPTMR is disabled or a logic 1 is written to it.
    */
   static LptmrCompareFlag getEventFlag() {
      return LptmrCompareFlag(lptmr->CSR&LPTMR_CSR_TCF_MASK);
   }
   
   /**
    * Clear Timer Compare Flag
    * (lptmr_csr_tcf)
    *
    * Flag is set when the LPTMR is enabled and the CNR equals the CMR and increments.
    * Flag is cleared when the LPTMR is disabled or a logic 1 is written to it.
    */
   static void clearEventFlag() {
      // w1c and mixed register
      lptmr->CSR = lptmr->CSR|LPTMR_CSR_TCF_MASK;
   }
   
   /**
    * Set Timer action on event
    * (lptmr_csr_tie)
    *
    * @param lptmrEventAction Enables LPTMR interrupts
    */
   static void setEventAction(LptmrEventAction lptmrEventAction) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TIE_MASK) | uint32_t(lptmrEventAction);
   }
   
   /**
    * Get Timer action on event
    * (lptmr_csr_tie)
    *
    * @return Enables LPTMR interrupts
    */
   static LptmrEventAction getEventAction() {
      return LptmrEventAction(lptmr->CSR&LPTMR_CSR_TIE_MASK);
   }
   
   /**
    * Set Input Pin
    * (lptmr_csr_tps)
    *
    * @param lptmrInput Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   static void setInputSelect(LptmrInput lptmrInput) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TPS_MASK) | uint32_t(lptmrInput);
   }
   
   /**
    * Get Input Pin
    * (lptmr_csr_tps)
    *
    * @return Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   static LptmrInput getInputSelect() {
      return LptmrInput(lptmr->CSR&LPTMR_CSR_TPS_MASK);
   }
   
   /**
    * Set Pin Polarity
    * (lptmr_csr_tpp)
    *
    * @param lptmrInputEdge Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   static void setInputEdge(LptmrInputEdge lptmrInputEdge) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TPP_MASK) | uint32_t(lptmrInputEdge);
   }
   
   /**
    * Get Pin Polarity
    * (lptmr_csr_tpp)
    *
    * @return Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   static LptmrInputEdge getInputEdge() {
      return LptmrInputEdge(lptmr->CSR&LPTMR_CSR_TPP_MASK);
   }
   
   /**
    * Set Counter Action on Compare Event
    * (lptmr_csr_tfc)
    *
    * @param lptmrCounterActionOnEvent Counter action when compare event occurs
    *        The counter can continue counting or be reset to zero.
    *        Should only be altered when timer is disabled.
    */
   static void setCounterActionOnEvent(LptmrCounterActionOnEvent lptmrCounterActionOnEvent) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TFC_MASK) | uint32_t(lptmrCounterActionOnEvent);
   }
   
   /**
    * Get Counter Action on Compare Event
    * (lptmr_csr_tfc)
    *
    * @return Counter action when compare event occurs
    *        The counter can continue counting or be reset to zero.
    *        Should only be altered when timer is disabled.
    */
   static LptmrCounterActionOnEvent getCounterActionOnEvent() {
      return LptmrCounterActionOnEvent(lptmr->CSR&LPTMR_CSR_TFC_MASK);
   }
   
   /**
    * Set Operation mode of the LPTMR
    * (lptmr_csr_tms)
    *
    * @param lptmrMode Selects between timer Interval and Pulse Counting
    *        Should only be altered when timer is disabled.
    */
   static void setMode(LptmrMode lptmrMode) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TMS_MASK) | uint32_t(lptmrMode);
   }
   
   /**
    * Get Operation mode of the LPTMR
    * (lptmr_csr_tms)
    *
    * @return Selects between timer Interval and Pulse Counting
    *        Should only be altered when timer is disabled.
    */
   static LptmrMode getMode() {
      return LptmrMode(lptmr->CSR&LPTMR_CSR_TMS_MASK);
   }
   
   /**
    * Set Timer Enable
    * (lptmr_csr_ten)
    *
    * @param lptmrCsrTen Enables timer
    */
   static void setEnable(LptmrCsrTen lptmrCsrTen) {
      lptmr->CSR = (lptmr->CSR&~LPTMR_CSR_TEN_MASK) | uint32_t(lptmrCsrTen);
   }
   
   /**
    * Get Timer Enable
    * (lptmr_csr_ten)
    *
    * @return Enables timer
    */
   static LptmrCsrTen getEnable() {
      return LptmrCsrTen(lptmr->CSR&LPTMR_CSR_TEN_MASK);
   }
   
   /**
    * Set Input Pin and Pin Polarity
    * (lptmr_csr_tps,lptmr_csr_tpp)
    *
    * @param lptmrInput     Input source to be used in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    * @param lptmrInputEdge Polarity of the input source in Pulse Counter mode
    *        Should only be altered when timer is disabled.
    */
   static void setInput(
         LptmrInput     lptmrInput,
         LptmrInputEdge lptmrInputEdge = LptmrInputEdge_Rising) {
      lptmr->CSR = (lptmr->CSR&~(LPTMR_CSR_TPS_MASK|LPTMR_CSR_TPP_MASK)) | uint32_t(lptmrInput|lptmrInputEdge);
   }
   
   /**
    * Set Clock source for LPTMR
    * (lptmr_psr_pcs)
    *
    * @param lptmrClockSel Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    */
   static void setClockSource(LptmrClockSel lptmrClockSel) {
      lptmr->PSR = (lptmr->PSR&~LPTMR_PSR_PCS_MASK) | uint32_t(lptmrClockSel);
   }
   
   /**
    * Get Clock source for LPTMR
    * (lptmr_psr_pcs)
    *
    * @return Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    */
   static LptmrClockSel getClockSource() {
      return LptmrClockSel(lptmr->PSR&LPTMR_PSR_PCS_MASK);
   }
   
   /**
    * Set Timer Compare Value
    * (lptmr_cmr_compare)
    *
    * @param ticks Comparison value
    *        The timer comparison flag is set when the counter reaches this value and increments. 
    *        The hardware trigger will assert until the next time the counter increments. 
    *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
    *        The CMR must only be altered when timer is disabled or when TCF is set.
    */
   static void setCompareThreshold(const Ticks& ticks) {
      lptmr->CMR = (lptmr->CMR&~LPTMR_CMR_COMPARE_MASK) | uint32_t(LPTMR_CMR_COMPARE(ticks));
   }
   
   /**
    * Get Timer Compare Value
    * (lptmr_cmr_compare)
    *
    * @return Comparison value
    *        The timer comparison flag is set when the counter reaches this value and increments. 
    *        The hardware trigger will assert until the next time the counter increments. 
    *        This value determines the period in TimeInterval mode or the event time in Pulse Counting mode
    *        The CMR must only be altered when timer is disabled or when TCF is set.
    */
   static Ticks getCompareThreshold() {
      return Ticks((lptmr->CMR&LPTMR_CMR_COMPARE_MASK)>>LPTMR_CMR_COMPARE_SHIFT);
   }
   
   /**
    * Set Clock source for LPTMR and Prescaler Value
    * (lptmr_psr_pcs,lptmr_psr_prescaler)
    *
    * These settings are used for the clock prescaler in timer mode.
    *
    * @param lptmrClockSel Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    * @param lptmrPrescale Configures the size of the Prescaler in Time Interval mode
    *        Should only be altered when timer is disabled.
    */
   static void setClock(
         LptmrClockSel lptmrClockSel,
         LptmrPrescale lptmrPrescale) {
   
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
      lptmr->PSR   = lptmrClockSel|lptmrPrescale;
      lptmr->CSR   = csr;
   }

   /**
    * Set Clock source for LPTMR and Filter Value
    * (lptmr_psr_pcs,lptmr_psr_glitchFilter)
    *
    * These settings are used for the glitch filter in pulse-counting mode.
    *
    * @param lptmrClockSel     Selects the clock source for LPTMR
    *        Should only be altered when timer is disabled.
    * @param lptmrGlitchFilter Configures the size of the glitch filter in Pulse Counting mode
    *        Should only be altered when timer is disabled.
    */
   static void setClock(
         LptmrClockSel     lptmrClockSel,
         LptmrGlitchFilter lptmrGlitchFilter) {
   
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
      lptmr->PSR   = lptmrClockSel|lptmrGlitchFilter;
      lptmr->CSR   = csr;
   }

   /**
    * Get Clock source for LPTMR frequency
    * (lptmr_psr_pcs)
    *
    * @return Clock frequency in Hz
    */
   static uint32_t getInputClockFrequency() {
   
      return LptmrBasicInfo::getInputClockFrequency(LptmrClockSel(LPTMR_PSR_PCS_MASK&lptmr->PSR));
   }
   
   /**
    * Get clock frequency after prescaler
    * (lptmr_psr_pcs)
    *
    * @return Frequency as a float in Hz
    */
   static float getClockFrequencyF() {
   
      float freq = getInputClockFrequency();
      if (lptmr->PSR&LPTMR_PSR_PBYP_MASK) {
         return freq;
      }
      return freq/(1<<(((lptmr->PSR&LPTMR_PSR_PRESCALE_MASK)>>LPTMR_PSR_PRESCALE_SHIFT)+1));
   }
   
   /**
    * Get clock frequency
    * (lptmr_psr_pcs)
    *
    * @return Frequency as a uint32_t in Hz (may underflow)
    */
   static uint32_t getClockFrequency() {
   
      uint32_t freq = getInputClockFrequency();
      if (lptmr->PSR&LPTMR_PSR_PBYP_MASK) {
         return freq;
      }
      return freq/(1<<(((lptmr->PSR&LPTMR_PSR_PRESCALE_MASK)>>LPTMR_PSR_PRESCALE_SHIFT)+1));
   }
   
   /**
    * Converts a number in ticks to time in microseconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in microseconds
    *
    * @note Assumes prescale has been chosen appropriately.
    * @note Rudimentary range checking only. Sets error code.
    */
   static uint32_t convertTicksToMicroseconds(Ticks ticks) {
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (((uint64_t)ticks)*1000000)/(unsigned)tickRate;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Converts a number in ticks to time in milliseconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in milliseconds
    *
    * @note Assumes prescale has been chosen appropriately.
    * @note Rudimentary range checking only. Sets error code.
    */
   static unsigned convertTicksToMilliseconds(Ticks ticks) {
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (((uint64_t)ticks)*1000)/(unsigned)tickRate;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return unsigned(rv);
   }
   
   /**
    * Converts a number in ticks to time in seconds.
    *
    * @param[in]  ticks Time in ticks
    *
    * @return Time in seconds (as float)
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   static Seconds convertTicksToSeconds(Ticks ticks) {
      float tickRate = getClockFrequencyF();
      return Seconds(((float)ticks)/tickRate);
   }
   
   /**
    * Converts a time in microseconds to number of ticks.
    *
    * @param[in]  time Time in microseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   static Ticks convertMicrosecondsToTicks(int time) {
   
      // Calculate period
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (unsigned)((uint64_t)time*tickRate)/1000000;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   /**
    * Converts a time in milliseconds to number of ticks.
    *
    * @param[in]  time Time in milliseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen appropriately.
    */
   static Ticks convertMillisecondsToTicks(int time) {
   
      // Calculate period
      uint32_t tickRate = getClockFrequency();
      uint64_t rv       = (unsigned)((uint64_t)time*tickRate)/1000;
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   
   /**
    * Converts a time in seconds to number of ticks
    *
    * @param[in]  time Time in seconds (float!)
    *
    * @return Time in ticks
    *
    * @note Uses floating point
    * @note Rudimentary range checking only. Sets error code.
    */
   static Ticks convertSecondsToTicks(Seconds time) {
   
      // Calculate period
      float    tickRate = getClockFrequencyF();
      uint64_t rv       = (unsigned)((float)time*tickRate);
   
#ifdef DEBUG_BUILD
      if (rv > UINT_MAX) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return Ticks(uint32_t(rv));
   }
   
   /**
    * Calculate filter information based on desired interval
    * This calculates a clock prescaler so that the filter interval is at least the given value.
    *
    * @param[in]     interval   Desired filter interval
    * @param[inout]  psr        Input: psr.pcs Output: updated with psr.prescale and psr.pbyp
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for psr.prescale and psr.pbyp
    */
   static ErrorCode calculateFilterValues(Seconds interval, uint8_t &psr) {
   
      float    inputClock = LptmrBasicInfo::getInputClockFrequency(LptmrClockSel(psr&LPTMR_PSR_PCS_MASK));
      int      prescaleFactor=1;
      uint32_t prescalerValue=0;
      while (prescalerValue<=16) {
         if ((float)(interval*prescaleFactor) < inputClock) {
            psr  = (psr&LPTMR_PSR_PCS_MASK)|LPTMR_PSR_PRESCALE(prescalerValue-1)|LPTMR_PSR_PBYP(prescalerValue==0);
            return E_NO_ERROR;
         }
         prescalerValue++;
         prescaleFactor <<= 1;
      }
      // Too long a duration
      return setAndCheckErrorCode(E_TOO_LARGE);
   }
   
   /**
    * Set period of timer.
    *
    * @param[in]  period Period in seconds as a float
    *
    * @note Will enable and adjust the pre-scaler to appropriate value.

    *       The clock source should be selected by setClock() before using this function.
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for psr.prescale and psr.pbyp
    */
   static ErrorCode setPeriod(Seconds period) {
   
      uint8_t  psr = lptmr->PSR;
      uint32_t cmr;
      ErrorCode rc = LptmrBasicInfo::calculateDurationValues(period, psr, cmr);
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable before changing clock
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
   
      lptmr->CMR  = cmr;
      lptmr->PSR  = psr;
   
      lptmr->CSR  = csr;
   
      return E_NO_ERROR;
   }
   
   /**
    * Set glitch filter interval.
    * This adjusts the clock prescaler so that the filter interval is at least the given value.
    *
    * @param[in]  interval Interval in seconds as a float
    *
    * @note Will enable and adjust the pre-scaler to appropriate value.

    *       The clock source should be selected by setClock() before using this function.
    *
    * @return E_NO_ERROR      => Success
    * @return E_ILLEGAL_PARAM => Failed to find suitable values for PBYP & PRESCALE
    */
   static ErrorCode setFilterInterval(Seconds interval) {
   
      uint8_t  psr = lptmr->PSR;
   
      ErrorCode rc = calculateFilterValues(interval, psr);
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable LPTMR before prescale change
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      (void)(lptmr->CSR);
   
      lptmr->PSR  = psr;
   
      lptmr->CSR  = csr;
   
      return E_NO_ERROR;
   }
   
   /**
    * Get timer counter value
    *
    * @return Timer value in ticks.
    */
   static Ticks getCounterValue() {
      // It is necessary to write to the CNR to capture current value
      lptmr->CNR = 0;
      return (Ticks)(lptmr->CNR);
   }
   
   /**
    * Restarts the counter
    * This restarts the timer by disabling and re-enabling with the same configuration
    */
   static void restart() {
      uint32_t csr = lptmr->CSR;
      lptmr->CSR   = csr&~LPTMR_CSR_TEN_MASK;
      lptmr->CSR   = csr;
   }
   
   /**
    * Information describing the priority and callback function for each interrupt
    */
   typedef InitVectors<TimeIntervalModeInit, CallbackFunction, int, 1> TimeIntervalModeInit;
   typedef InitVectors<PulseCountingModeInit, CallbackFunction, int, 1> PulseCountingModeInit;
   
   /*
    *   Default Constructor
    */
   Lptmr0Info() : LptmrBasicInfo(lptmr) {
      defaultConfigure();
   }
   
   /*
    *   Constructor
    */
   Lptmr0Info(const TimeIntervalModeInit &init) : LptmrBasicInfo(lptmr) {
      configure(init);
   }
   
   /*
    *   Constructor
    */
   Lptmr0Info(const PulseCountingModeInit &init) : LptmrBasicInfo(lptmr) {
      configure(init);
   }
   
   /**
    * Configure with default settings.
    * Configuration determined from Configure.usbdmProject
    */
   static ErrorCode defaultConfigure() {
   
      return configure(DefaultInitValue);
   }
   
   /**
    * Configure LPTMR from values specified in init
    *
    * @param init Class containing initialisation values
    */
   static ErrorCode configure(const TimeIntervalModeInit &init) {
   
      // Ensure no interrupts during configuration
      disableNvicInterrupts();
   
      // Enable peripheral
      enable();
   
      ErrorCode rc = LptmrBasicInfo::configure(lptmr, init);
      if (rc != E_NO_ERROR) {
         return rc;
      }
   
      // Configure call-back
      setCallback(init.callbacks[0]);
      enableNvicInterrupts(init.priorities[0]);
   
      return rc;
   }
   
   /**
    * Configure LPTMR from values specified in init
    *
    * @param init Class containing initialisation values
    */
   static ErrorCode configure(const PulseCountingModeInit &init) {
   
      // Enable peripheral
      enable();
   
      // Configure call-back
      if (init.callbacks[0] != nullptr) {
         setCallback(init.callbacks[0]);
         enableNvicInterrupts(init.priorities[0]);
      }
   
      return LptmrBasicInfo::configure(lptmr, init);
   }
   
   /**
    * Default value for Lptmr0 in Time Interval Mode
    * This value is created from Configure.usbdmProject settings (Peripheral Parameters->LPTMR)
    */
   static constexpr TimeIntervalModeInit DefaultInitValue {

      NvicPriority_Normal ,                  // (irqLevel)                 IRQ priority level - Normal
      unhandledCallback,                     // (handlerName)              User declared event handler
   
      LptmrCounterActionOnEvent_Reset ,      // (lptmr_csr_tfc)            Counter Action on Compare Event - Counter is reset on event
      LptmrEventAction_None ,                // (lptmr_csr_tie)            Timer action on event - None
      LptmrClockSel_Lpoclk ,                 // (lptmr_psr_pcs)            Clock source for LPTMR - Low power oscillator (LPO - 1kHz)
      LptmrPrescale_Direct ,                 // (lptmr_psr_prescaler)      Prescaler Value - Prescaler = 1
      65535_ticks,                           // (lptmr_cmr_compare)        Timer Compare Value
   };
   
}; // class Lptmr0Info



#ifdef PCC_PCC_LPTMR0_CGC_MASK
/**
 * Select the LPTMR clock source which determines count speed or glitch filtering
 */
enum LptmrClockSel {
   LptmrClockSel_SircDiv2Clk  = LPTMR_PSR_PCS(0), ///< Slow Internal Reference Div 2 Clock (SIRCDIV2_CLK)
   LptmrClockSel_Lpo1Kclk     = LPTMR_PSR_PCS(1), ///< Low power oscillator 1kHz (LPO1K_CLK)
   LptmrClockSel_Rtcclk       = LPTMR_PSR_PCS(2), ///< 32kHz Clock Source (RTC_CLK)
   LptmrClockSel_PccLptmrClk  = LPTMR_PSR_PCS(3), ///< Clock from PCC_LPTMRx multiplexor (PCC)
   LptmrClockSel_Default      = LptmrClockSel_Lpo1Kclk,
};
#endif


   /**
    * Class representing LPTMR instance
    */
   typedef LptmrBasicInfo Lptmr;
   /**
    * Class representing LPTMR0
    */
   typedef Lptmr0Info Lptmr0;
   

   

#endif // /LPTMR/_BasicInfoGuard
/**
 * End LPTMR_Group
 * @}
 */

} // End namespace USBDM

#endif /* HEADER_LPTMR_H */
