/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "../Project_Headers/error.h"
#include "../Project_Headers/pin_mapping.h"
#include "../Project_Headers/delay.h"
#include "../Project_Headers/console.h"
#include "../Project_Headers/gpio.h"

#include "../Project_Headers/gpio.h"
#include "../Project_Headers/lptmr.h"
#include "../Project_Headers/tpm.h"


// User includes
// None

namespace USBDM {

// User declarations
// None

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

// Hardware declarations

typedef USBDM::GpioA<12,ActiveHigh>                          Digital_D3;                                   // PTA12(D3)

typedef USBDM::GpioA<4,ActiveHigh>                           Digital_D4;                                   // PTA4(D4)

typedef USBDM::GpioA<12,ActiveHigh>                          ResultPin;                                    // PTA12(D3)

typedef USBDM::GpioA<16,ActiveHigh>                          Digital_D28;                                  // PTA16(D28)

typedef USBDM::GpioA<17,ActiveHigh>                          Digital_D29;                                  // PTA17(D29)

typedef USBDM::GpioA<5,ActiveHigh>                           Digital_D5;                                   // PTA5(D5)

typedef USBDM::GpioA<13,ActiveHigh>                          Digital_D8;                                   // PTA13(D8)

typedef USBDM::GpioB<11,ActiveHigh>                          Digital_A17;                                  // PTB11(A17)

typedef USBDM::GpioB<10,ActiveHigh>                          Digital_A18;                                  // PTB10(A18)

typedef USBDM::GpioB<0,ActiveHigh>                           Digital_A0;                                   // PTB0(A0)

typedef USBDM::GpioB<9,ActiveHigh>                           Digital_A19;                                  // PTB9(A19)

typedef USBDM::GpioB<1,ActiveHigh>                           Digital_A1;                                   // PTB1(A1)

/// Red LED
typedef USBDM::GpioB<18,ActiveLow>                           RGB_Red;                                      // PTB18(LED_RED)

/// Green LED
typedef USBDM::GpioB<19,ActiveLow>                           RGB_Green;                                    // PTB19(LED_GREEN)

typedef USBDM::GpioB<0,ActiveHigh>                           CapturePin;                                   // PTB0(A0)

typedef USBDM::GpioB<8,ActiveHigh>                           Digital_A20;                                  // PTB8(A20)

typedef USBDM::GpioB<2,ActiveHigh>                           Digital_A2;                                   // PTB2(A2)

typedef USBDM::GpioB<3,ActiveHigh>                           Digital_A3;                                   // PTB3(A3)

typedef USBDM::GpioC<5,ActiveHigh>                           Digital_D20;                                  // PTC5(D20)

typedef USBDM::GpioC<6,ActiveHigh>                           Digital_D21;                                  // PTC6(D21)

typedef USBDM::GpioC<10,ActiveHigh>                          Digital_D22;                                  // PTC10(D22)

typedef USBDM::GpioC<11,ActiveHigh>                          Digital_D23;                                  // PTC11(D23)

typedef USBDM::GpioC<12,ActiveHigh>                          Digital_D24;                                  // PTC12(D24)

typedef USBDM::GpioC<13,ActiveHigh>                          Digital_D25;                                  // PTC13(D25)

typedef USBDM::GpioC<16,ActiveHigh>                          Digital_D26;                                  // PTC16(D26)

typedef USBDM::GpioC<7,ActiveHigh>                           Digital_D16;                                  // PTC7(D16)

typedef USBDM::GpioC<17,ActiveHigh>                          Digital_D27;                                  // PTC17(D27)

typedef USBDM::GpioC<0,ActiveHigh>                           Digital_D17;                                  // PTC0(D17)

typedef USBDM::GpioC<3,ActiveHigh>                           Digital_D18;                                  // PTC3(D18)

typedef USBDM::GpioC<4,ActiveHigh>                           Digital_D19;                                  // PTC4(D19)

typedef USBDM::GpioC<8,ActiveHigh>                           Digital_D6;                                   // PTC8(D6)

typedef USBDM::GpioC<2,ActiveHigh>                           Digital_A4;                                   // PTC2(A4)

typedef USBDM::GpioC<9,ActiveHigh>                           Digital_D7;                                   // PTC9(D7)

typedef USBDM::GpioC<1,ActiveHigh>                           Digital_A5;                                   // PTC1(A5)

typedef USBDM::GpioD<4,ActiveHigh>                           Digital_D2;                                   // PTD4(D2)

typedef USBDM::GpioD<1,ActiveHigh>                           DebugPin;                                     // PTD1(D13/LED_BLUE)

typedef USBDM::GpioD<1,ActiveHigh>                           RGB_Blue;                                     // PTD1(D13/LED_BLUE)

typedef USBDM::GpioD<5,ActiveHigh>                           Digital_D9;                                   // PTD5(D9)

typedef USBDM::GpioD<0,ActiveHigh>                           Digital_D10;                                  // PTD0(D10)

typedef USBDM::GpioD<6,ActiveHigh>                           Digital_D32;                                  // PTD6(D32)

typedef USBDM::GpioD<2,ActiveHigh>                           Digital_D11;                                  // PTD2(D11)

typedef USBDM::GpioD<7,ActiveHigh>                           Digital_D33;                                  // PTD7(D33)

typedef USBDM::GpioD<3,ActiveHigh>                           Digital_D12;                                  // PTD3(D12)

/// Blue LED
typedef USBDM::GpioD<1,ActiveHigh>                           Digital_D13;                                  // PTD1(D13/LED_BLUE)

typedef USBDM::GpioE<29,ActiveHigh>                          Digital_A10;                                  // PTE29(A10)

typedef USBDM::GpioE<30,ActiveHigh>                          Digital_A11;                                  // PTE30(A11)

typedef USBDM::GpioE<31,ActiveHigh>                          Digital_D30;                                  // PTE31(D30)

typedef USBDM::GpioE<5,ActiveHigh>                           Digital_A13;                                  // PTE5(A13)

typedef USBDM::GpioE<4,ActiveHigh>                           Digital_A14;                                  // PTE4(A14)

typedef USBDM::GpioE<3,ActiveHigh>                           Digital_A15;                                  // PTE3(A15)

typedef USBDM::GpioE<2,ActiveHigh>                           Digital_A16;                                  // PTE2(A16)

typedef USBDM::GpioE<0,ActiveHigh>                           Digital_D14;                                  // PTE0(D14)

typedef USBDM::GpioE<1,ActiveHigh>                           Digital_D15;                                  // PTE1(D15)

typedef USBDM::GpioE<20,ActiveHigh>                          Digital_A6;                                   // PTE20(A6)

typedef USBDM::GpioE<21,ActiveHigh>                          Digital_A7;                                   // PTE21(A7)

typedef USBDM::GpioE<22,ActiveHigh>                          Digital_A8;                                   // PTE22(A8)

typedef USBDM::GpioE<23,ActiveHigh>                          Digital_A9;                                   // PTE23(A9)

/// LPTMR, Low Power Timer
typedef Lptmr0                                               Timer;                                        

typedef PcrTable_T<TpmInfo, 0>                               TpmClkin0;                                    // PTC12(D24)

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
